package com.nali.spreader.dao;

import com.nali.spreader.model.StrategyGroup;
import com.nali.spreader.model.StrategyGroupExample;
import java.util.List;

public interface ICrudStrategyGroupDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    int countByExample(StrategyGroupExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    int deleteByExample(StrategyGroupExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    void insert(StrategyGroup record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    void insertSelective(StrategyGroup record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    List<StrategyGroup> selectByExample(StrategyGroupExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    StrategyGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    int updateByExampleSelective(StrategyGroup record, StrategyGroupExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    int updateByExample(StrategyGroup record, StrategyGroupExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    int updateByPrimaryKeySelective(StrategyGroup record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    int updateByPrimaryKey(StrategyGroup record);
}
