package com.nali.spreader.dao;

import com.nali.spreader.data.HelpEnumInfo;
import com.nali.spreader.data.HelpEnumInfoExample;
import java.util.List;

public interface ICrudHelpEnumInfoDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    int countByExample(HelpEnumInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    int deleteByExample(HelpEnumInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    Long insert(HelpEnumInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    Long insertSelective(HelpEnumInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    List<HelpEnumInfo> selectByExample(HelpEnumInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    HelpEnumInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    int updateByExampleSelective(HelpEnumInfo record, HelpEnumInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    int updateByExample(HelpEnumInfo record, HelpEnumInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    int updateByPrimaryKeySelective(HelpEnumInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_help_enum_info
     *
     * @ibatorgenerated Thu Nov 15 17:57:35 CST 2012
     */
    int updateByPrimaryKey(HelpEnumInfo record);
}
