package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudRegularJobResultDao;
import com.nali.spreader.model.RegularJobResult;
import com.nali.spreader.model.RegularJobResultExample;

@Repository
public class CrudRegularJobResultDao implements ICrudRegularJobResultDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public CrudRegularJobResultDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public int countByExample(RegularJobResultExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_regular_job_result.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public int deleteByExample(RegularJobResultExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_regular_job_result.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        RegularJobResult key = new RegularJobResult();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_regular_job_result.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void insert(RegularJobResult record) {
        getSqlMapClientTemplate().insert("spreader_tb_regular_job_result.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void insertSelective(RegularJobResult record) {
        getSqlMapClientTemplate().insert("spreader_tb_regular_job_result.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<RegularJobResult> selectByExampleWithBLOBs(RegularJobResultExample example) {
        List<RegularJobResult> list = getSqlMapClientTemplate().queryForList("spreader_tb_regular_job_result.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<RegularJobResult> selectByExampleWithoutBLOBs(RegularJobResultExample example) {
        List<RegularJobResult> list = getSqlMapClientTemplate().queryForList("spreader_tb_regular_job_result.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public RegularJobResult selectByPrimaryKey(Long id) {
        RegularJobResult key = new RegularJobResult();
        key.setId(id);
        RegularJobResult record = (RegularJobResult) getSqlMapClientTemplate().queryForObject("spreader_tb_regular_job_result.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public int updateByExampleSelective(RegularJobResult record, RegularJobResultExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_regular_job_result.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public int updateByExampleWithBLOBs(RegularJobResult record, RegularJobResultExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_regular_job_result.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public int updateByExampleWithoutBLOBs(RegularJobResult record, RegularJobResultExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_regular_job_result.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public int updateByPrimaryKeySelective(RegularJobResult record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_regular_job_result.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public int updateByPrimaryKeyWithBLOBs(RegularJobResult record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_regular_job_result.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public int updateByPrimaryKeyWithoutBLOBs(RegularJobResult record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_regular_job_result.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_regular_job_result
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private static class UpdateByExampleParms extends RegularJobResultExample {
        private Object record;

        public UpdateByExampleParms(Object record, RegularJobResultExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}