package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudStrategyGroupDao;
import com.nali.spreader.model.StrategyGroup;
import com.nali.spreader.model.StrategyGroupExample;

@Repository
public class CrudStrategyGroupDao implements ICrudStrategyGroupDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Thu Jan 05 15:58:51 CST 2012
     */
    public CrudStrategyGroupDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public int countByExample(StrategyGroupExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_strategy_group.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public int deleteByExample(StrategyGroupExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_strategy_group.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        StrategyGroup key = new StrategyGroup();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_strategy_group.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public void insert(StrategyGroup record) {
        getSqlMapClientTemplate().insert("spreader_tb_strategy_group.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public void insertSelective(StrategyGroup record) {
        getSqlMapClientTemplate().insert("spreader_tb_strategy_group.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<StrategyGroup> selectByExample(StrategyGroupExample example) {
        List<StrategyGroup> list = getSqlMapClientTemplate().queryForList("spreader_tb_strategy_group.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public StrategyGroup selectByPrimaryKey(Long id) {
        StrategyGroup key = new StrategyGroup();
        key.setId(id);
        StrategyGroup record = (StrategyGroup) getSqlMapClientTemplate().queryForObject("spreader_tb_strategy_group.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public int updateByExampleSelective(StrategyGroup record, StrategyGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_strategy_group.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public int updateByExample(StrategyGroup record, StrategyGroupExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_strategy_group.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public int updateByPrimaryKeySelective(StrategyGroup record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_strategy_group.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public int updateByPrimaryKey(StrategyGroup record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_strategy_group.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_strategy_group
     *
     * @ibatorgenerated Fri Jan 06 17:05:12 CST 2012
     */
    private static class UpdateByExampleParms extends StrategyGroupExample {

        private Object record;

        public UpdateByExampleParms(Object record, StrategyGroupExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
