package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudIpRecordDao;
import com.nali.spreader.model.IpRecord;
import com.nali.spreader.model.IpRecordExample;

@Repository
public class CrudIpRecordDao implements ICrudIpRecordDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public CrudIpRecordDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public int countByExample(IpRecordExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_ip_record.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public int deleteByExample(IpRecordExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_ip_record.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        IpRecord key = new IpRecord();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_ip_record.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public Long insert(IpRecord record) {
        Object newKey = getSqlMapClientTemplate().insert("spreader_tb_ip_record.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public Long insertSelective(IpRecord record) {
        Object newKey = getSqlMapClientTemplate().insert("spreader_tb_ip_record.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<IpRecord> selectByExample(IpRecordExample example) {
        List<IpRecord> list = getSqlMapClientTemplate().queryForList("spreader_tb_ip_record.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public IpRecord selectByPrimaryKey(Long id) {
        IpRecord key = new IpRecord();
        key.setId(id);
        IpRecord record = (IpRecord) getSqlMapClientTemplate().queryForObject("spreader_tb_ip_record.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public int updateByExampleSelective(IpRecord record, IpRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_ip_record.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public int updateByExample(IpRecord record, IpRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_ip_record.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public int updateByPrimaryKeySelective(IpRecord record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_ip_record.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public int updateByPrimaryKey(IpRecord record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_ip_record.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_ip_record
     *
     * @ibatorgenerated Fri Sep 07 13:47:33 CST 2012
     */
    private static class UpdateByExampleParms extends IpRecordExample {
        private Object record;

        public UpdateByExampleParms(Object record, IpRecordExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}