package com.nali.spreader.dao;

import java.util.List;
import com.nali.spreader.model.ClientTask;
import com.nali.spreader.model.ClientTaskExample;

public interface ICrudClientTaskDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    int countByExample(ClientTaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    int deleteByExample(ClientTaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    void insert(ClientTask record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    void insertSelective(ClientTask record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    List<ClientTask> selectByExampleWithBLOBs(ClientTaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    List<ClientTask> selectByExampleWithoutBLOBs(ClientTaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    ClientTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    int updateByExampleSelective(ClientTask record, ClientTaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    int updateByExampleWithBLOBs(ClientTask record, ClientTaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    int updateByExampleWithoutBLOBs(ClientTask record, ClientTaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    int updateByPrimaryKeySelective(ClientTask record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    int updateByPrimaryKeyWithBLOBs(ClientTask record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_task
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    int updateByPrimaryKeyWithoutBLOBs(ClientTask record);
}
