package com.nali.spreader.dao;


import java.util.List;

import com.nali.spreader.model.RegularJob;
import com.nali.spreader.model.RegularJobExample;

public interface ICrudRegularJobDao {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    int countByExample(RegularJobExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    int deleteByExample(RegularJobExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    Long insert(RegularJob record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    Long insertSelective(RegularJob record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    List<RegularJob> selectByExampleWithBLOBs(RegularJobExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    List<RegularJob> selectByExampleWithoutBLOBs(RegularJobExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    RegularJob selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    int updateByExampleSelective(RegularJob record, RegularJobExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    int updateByExampleWithBLOBs(RegularJob record, RegularJobExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    int updateByExampleWithoutBLOBs(RegularJob record, RegularJobExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    int updateByPrimaryKeySelective(RegularJob record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    int updateByPrimaryKeyWithBLOBs(RegularJob record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_regular_job
     *
     * @ibatorgenerated Mon Jul 23 13:48:27 CST 2012
     */
    int updateByPrimaryKeyWithoutBLOBs(RegularJob record);
}