package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudRobotContentDao;
import com.nali.spreader.model.RobotContent;
import com.nali.spreader.model.RobotContentExample;

@Repository
public class CrudRobotContentDao implements ICrudRobotContentDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Tue Mar 13 15:31:15 CST 2012
     */
    public CrudRobotContentDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public int countByExample(RobotContentExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_robot_content.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public int deleteByExample(RobotContentExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_robot_content.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        RobotContent key = new RobotContent();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_robot_content.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public void insert(RobotContent record) {
        getSqlMapClientTemplate().insert("spreader_tb_robot_content.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public void insertSelective(RobotContent record) {
        getSqlMapClientTemplate().insert("spreader_tb_robot_content.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<RobotContent> selectByExample(RobotContentExample example) {
        List<RobotContent> list = getSqlMapClientTemplate().queryForList("spreader_tb_robot_content.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public RobotContent selectByPrimaryKey(Long id) {
        RobotContent key = new RobotContent();
        key.setId(id);
        RobotContent record = (RobotContent) getSqlMapClientTemplate().queryForObject("spreader_tb_robot_content.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public int updateByExampleSelective(RobotContent record, RobotContentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_content.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public int updateByExample(RobotContent record, RobotContentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_content.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public int updateByPrimaryKeySelective(RobotContent record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_content.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public int updateByPrimaryKey(RobotContent record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_content.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_robot_content
     *
     * @ibatorgenerated Thu Mar 15 15:24:53 CST 2012
     */
    private static class UpdateByExampleParms extends RobotContentExample {

        private Object record;

        public UpdateByExampleParms(Object record, RobotContentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
