package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudAppPurchaseDao;
import com.nali.spreader.data.AppPurchase;
import com.nali.spreader.data.AppPurchaseExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudAppPurchaseDao implements ICrudAppPurchaseDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public CrudAppPurchaseDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public int countByExample(AppPurchaseExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_app_purchase.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public int deleteByExample(AppPurchaseExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_app_purchase.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public int deleteByPrimaryKey(Long appid) {
        AppPurchase key = new AppPurchase();
        key.setAppid(appid);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_app_purchase.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public void insert(AppPurchase record) {
        getSqlMapClientTemplate().insert("spreader_tb_app_purchase.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public void insertSelective(AppPurchase record) {
        getSqlMapClientTemplate().insert("spreader_tb_app_purchase.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<AppPurchase> selectByExampleWithBLOBs(AppPurchaseExample example) {
        List<AppPurchase> list = getSqlMapClientTemplate().queryForList("spreader_tb_app_purchase.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<AppPurchase> selectByExampleWithoutBLOBs(AppPurchaseExample example) {
        List<AppPurchase> list = getSqlMapClientTemplate().queryForList("spreader_tb_app_purchase.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public AppPurchase selectByPrimaryKey(Long appid) {
        AppPurchase key = new AppPurchase();
        key.setAppid(appid);
        AppPurchase record = (AppPurchase) getSqlMapClientTemplate().queryForObject("spreader_tb_app_purchase.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public int updateByExampleSelective(AppPurchase record, AppPurchaseExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_app_purchase.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public int updateByExampleWithBLOBs(AppPurchase record, AppPurchaseExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_app_purchase.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public int updateByExampleWithoutBLOBs(AppPurchase record, AppPurchaseExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_app_purchase.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public int updateByPrimaryKeySelective(AppPurchase record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_app_purchase.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public int updateByPrimaryKeyWithBLOBs(AppPurchase record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_app_purchase.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public int updateByPrimaryKeyWithoutBLOBs(AppPurchase record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_app_purchase.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_app_purchase
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    private static class UpdateByExampleParms extends AppPurchaseExample {
        private Object record;

        public UpdateByExampleParms(Object record, AppPurchaseExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}