package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudContentKeywordDao;
import com.nali.spreader.data.ContentKeyword;
import com.nali.spreader.data.ContentKeywordExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudContentKeywordDao implements ICrudContentKeywordDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public CrudContentKeywordDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public int countByExample(ContentKeywordExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_content_keyword.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public int deleteByExample(ContentKeywordExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_content_keyword.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        ContentKeyword key = new ContentKeyword();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_content_keyword.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public void insert(ContentKeyword record) {
        getSqlMapClientTemplate().insert("spreader_tb_content_keyword.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public void insertSelective(ContentKeyword record) {
        getSqlMapClientTemplate().insert("spreader_tb_content_keyword.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<ContentKeyword> selectByExample(ContentKeywordExample example) {
        List<ContentKeyword> list = getSqlMapClientTemplate().queryForList("spreader_tb_content_keyword.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public ContentKeyword selectByPrimaryKey(Long id) {
        ContentKeyword key = new ContentKeyword();
        key.setId(id);
        ContentKeyword record = (ContentKeyword) getSqlMapClientTemplate().queryForObject("spreader_tb_content_keyword.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public int updateByExampleSelective(ContentKeyword record, ContentKeywordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_content_keyword.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public int updateByExample(ContentKeyword record, ContentKeywordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_content_keyword.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public int updateByPrimaryKeySelective(ContentKeyword record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_content_keyword.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public int updateByPrimaryKey(ContentKeyword record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_content_keyword.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_content_keyword
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    private static class UpdateByExampleParms extends ContentKeywordExample {
        private Object record;

        public UpdateByExampleParms(Object record, ContentKeywordExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}