package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudAppleSuperUserDao;
import com.nali.spreader.data.AppleSuperUser;
import com.nali.spreader.data.AppleSuperUserExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudAppleSuperUserDao implements ICrudAppleSuperUserDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public CrudAppleSuperUserDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public int countByExample(AppleSuperUserExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_apple_super_user.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public int deleteByExample(AppleSuperUserExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_apple_super_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        AppleSuperUser key = new AppleSuperUser();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_apple_super_user.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public void insert(AppleSuperUser record) {
        getSqlMapClientTemplate().insert("spreader_tb_apple_super_user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public void insertSelective(AppleSuperUser record) {
        getSqlMapClientTemplate().insert("spreader_tb_apple_super_user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<AppleSuperUser> selectByExample(AppleSuperUserExample example) {
        List<AppleSuperUser> list = getSqlMapClientTemplate().queryForList("spreader_tb_apple_super_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public AppleSuperUser selectByPrimaryKey(Long id) {
        AppleSuperUser key = new AppleSuperUser();
        key.setId(id);
        AppleSuperUser record = (AppleSuperUser) getSqlMapClientTemplate().queryForObject("spreader_tb_apple_super_user.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public int updateByExampleSelective(AppleSuperUser record, AppleSuperUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_apple_super_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public int updateByExample(AppleSuperUser record, AppleSuperUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_apple_super_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public int updateByPrimaryKeySelective(AppleSuperUser record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_apple_super_user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public int updateByPrimaryKey(AppleSuperUser record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_apple_super_user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_apple_super_user
     *
     * @ibatorgenerated Mon Apr 08 17:25:13 CST 2013
     */
    private static class UpdateByExampleParms extends AppleSuperUserExample {
        private Object record;

        public UpdateByExampleParms(Object record, AppleSuperUserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}