package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudCareerDao;
import com.nali.spreader.data.Career;
import com.nali.spreader.data.CareerExample;

@Repository
public class CrudCareerDao implements ICrudCareerDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Sat Jul 30 16:58:55 CST 2011
     */
    public CrudCareerDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public int countByExample(CareerExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_career.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public int deleteByExample(CareerExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_career.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public int deleteByPrimaryKey(Long id) {
        Career key = new Career();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_career.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public void insert(Career record) {
        getSqlMapClientTemplate().insert("spreader_tb_career.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public void insertSelective(Career record) {
        getSqlMapClientTemplate().insert("spreader_tb_career.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<Career> selectByExample(CareerExample example) {
        List<Career> list = getSqlMapClientTemplate().queryForList("spreader_tb_career.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public Career selectByPrimaryKey(Long id) {
        Career key = new Career();
        key.setId(id);
        Career record = (Career) getSqlMapClientTemplate().queryForObject("spreader_tb_career.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public int updateByExampleSelective(Career record, CareerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_career.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public int updateByExample(Career record, CareerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_career.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public int updateByPrimaryKeySelective(Career record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_career.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public int updateByPrimaryKey(Career record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_career.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_career
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    private static class UpdateByExampleParms extends CareerExample {

        private Object record;

        public UpdateByExampleParms(Object record, CareerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
