package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudYybPacketDao;
import com.nali.spreader.model.YybPacket;
import com.nali.spreader.model.YybPacketExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudYybPacketDao implements ICrudYybPacketDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public CrudYybPacketDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public int countByExample(YybPacketExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_yyb_packet.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public int deleteByExample(YybPacketExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_yyb_packet.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        YybPacket key = new YybPacket();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_yyb_packet.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public Long insert(YybPacket record) {
        Object newKey = getSqlMapClientTemplate().insert("spreader_tb_yyb_packet.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public Long insertSelective(YybPacket record) {
        Object newKey = getSqlMapClientTemplate().insert("spreader_tb_yyb_packet.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<YybPacket> selectByExample(YybPacketExample example) {
        List<YybPacket> list = getSqlMapClientTemplate().queryForList("spreader_tb_yyb_packet.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public YybPacket selectByPrimaryKey(Long id) {
        YybPacket key = new YybPacket();
        key.setId(id);
        YybPacket record = (YybPacket) getSqlMapClientTemplate().queryForObject("spreader_tb_yyb_packet.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public int updateByExampleSelective(YybPacket record, YybPacketExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_yyb_packet.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public int updateByExample(YybPacket record, YybPacketExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_yyb_packet.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public int updateByPrimaryKeySelective(YybPacket record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_yyb_packet.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public int updateByPrimaryKey(YybPacket record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_yyb_packet.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_yyb_packet
     *
     * @ibatorgenerated Fri Aug 23 14:09:51 CST 2013
     */
    private static class UpdateByExampleParms extends YybPacketExample {
        private Object record;

        public UpdateByExampleParms(Object record, YybPacketExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}