package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudClientReportDao;
import com.nali.spreader.model.ClientReport;
import com.nali.spreader.model.ClientReportExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudClientReportDao implements ICrudClientReportDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Wed May 08 10:05:15 CST 2013
     */
    public CrudClientReportDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Fri Jul 19 13:54:10 CST 2013
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Fri Jul 19 13:54:10 CST 2013
     */
    public int countByExample(ClientReportExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_client_report.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Fri Jul 19 13:54:10 CST 2013
     */
    public int deleteByExample(ClientReportExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_client_report.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Fri Jul 19 13:54:10 CST 2013
     */
    public void insert(ClientReport record) {
        getSqlMapClientTemplate().insert("spreader_tb_client_report.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Fri Jul 19 13:54:10 CST 2013
     */
    public void insertSelective(ClientReport record) {
        getSqlMapClientTemplate().insert("spreader_tb_client_report.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Fri Jul 19 13:54:10 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<ClientReport> selectByExample(ClientReportExample example) {
        List<ClientReport> list = getSqlMapClientTemplate().queryForList("spreader_tb_client_report.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Fri Jul 19 13:54:10 CST 2013
     */
    public int updateByExampleSelective(ClientReport record, ClientReportExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_client_report.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Fri Jul 19 13:54:10 CST 2013
     */
    public int updateByExample(ClientReport record, ClientReportExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_client_report.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Fri Jul 19 13:54:10 CST 2013
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_client_report
     *
     * @ibatorgenerated Fri Jul 19 13:54:10 CST 2013
     */
    private static class UpdateByExampleParms extends ClientReportExample {

        private Object record;

        public UpdateByExampleParms(Object record, ClientReportExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
