package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudNoticeDao;
import com.nali.spreader.data.Notice;
import com.nali.spreader.data.NoticeExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudNoticeDao implements ICrudNoticeDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Mon Jul 02 13:58:25 CST 2012
     */
    public CrudNoticeDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public int countByExample(NoticeExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_notice.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public int deleteByExample(NoticeExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_notice.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        Notice key = new Notice();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_notice.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public Long insert(Notice record) {
        Object newKey = getSqlMapClientTemplate().insert("spreader_tb_notice.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public Long insertSelective(Notice record) {
        Object newKey = getSqlMapClientTemplate().insert("spreader_tb_notice.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<Notice> selectByExample(NoticeExample example) {
        List<Notice> list = getSqlMapClientTemplate().queryForList("spreader_tb_notice.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public Notice selectByPrimaryKey(Long id) {
        Notice key = new Notice();
        key.setId(id);
        Notice record = (Notice) getSqlMapClientTemplate().queryForObject("spreader_tb_notice.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public int updateByExampleSelective(Notice record, NoticeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_notice.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public int updateByExample(Notice record, NoticeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_notice.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public int updateByPrimaryKeySelective(Notice record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_notice.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public int updateByPrimaryKey(Notice record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_notice.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_notice
     *
     * @ibatorgenerated Wed Jul 04 15:20:21 CST 2012
     */
    private static class UpdateByExampleParms extends NoticeExample {

        private Object record;

        public UpdateByExampleParms(Object record, NoticeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
