package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudAccountLogonDao;
import com.nali.spreader.data.AccountLogon;
import com.nali.spreader.data.AccountLogonExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudAccountLogonDao implements ICrudAccountLogonDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public CrudAccountLogonDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public int countByExample(AccountLogonExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_account_logon.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public int deleteByExample(AccountLogonExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_account_logon.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        AccountLogon key = new AccountLogon();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_account_logon.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public void insert(AccountLogon record) {
        getSqlMapClientTemplate().insert("spreader_tb_account_logon.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public void insertSelective(AccountLogon record) {
        getSqlMapClientTemplate().insert("spreader_tb_account_logon.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<AccountLogon> selectByExample(AccountLogonExample example) {
        List<AccountLogon> list = getSqlMapClientTemplate().queryForList("spreader_tb_account_logon.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public AccountLogon selectByPrimaryKey(Long id) {
        AccountLogon key = new AccountLogon();
        key.setId(id);
        AccountLogon record = (AccountLogon) getSqlMapClientTemplate().queryForObject("spreader_tb_account_logon.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public int updateByExampleSelective(AccountLogon record, AccountLogonExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_account_logon.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public int updateByExample(AccountLogon record, AccountLogonExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_account_logon.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public int updateByPrimaryKeySelective(AccountLogon record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_account_logon.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public int updateByPrimaryKey(AccountLogon record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_account_logon.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_account_logon
     *
     * @ibatorgenerated Mon Apr 16 14:34:58 CST 2012
     */
    private static class UpdateByExampleParms extends AccountLogonExample {
        private Object record;

        public UpdateByExampleParms(Object record, AccountLogonExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}