package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudWeiboAppealDao;
import com.nali.spreader.data.WeiboAppeal;
import com.nali.spreader.data.WeiboAppealExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudWeiboAppealDao implements ICrudWeiboAppealDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public CrudWeiboAppealDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public int countByExample(WeiboAppealExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_weibo_appeal.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public int deleteByExample(WeiboAppealExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_weibo_appeal.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public int deleteByPrimaryKey(Long uid) {
        WeiboAppeal key = new WeiboAppeal();
        key.setUid(uid);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_weibo_appeal.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public void insert(WeiboAppeal record) {
        getSqlMapClientTemplate().insert("spreader_tb_weibo_appeal.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public void insertSelective(WeiboAppeal record) {
        getSqlMapClientTemplate().insert("spreader_tb_weibo_appeal.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<WeiboAppeal> selectByExample(WeiboAppealExample example) {
        List<WeiboAppeal> list = getSqlMapClientTemplate().queryForList("spreader_tb_weibo_appeal.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public WeiboAppeal selectByPrimaryKey(Long uid) {
        WeiboAppeal key = new WeiboAppeal();
        key.setUid(uid);
        WeiboAppeal record = (WeiboAppeal) getSqlMapClientTemplate().queryForObject("spreader_tb_weibo_appeal.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public int updateByExampleSelective(WeiboAppeal record, WeiboAppealExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_weibo_appeal.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public int updateByExample(WeiboAppeal record, WeiboAppealExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_weibo_appeal.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public int updateByPrimaryKeySelective(WeiboAppeal record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_weibo_appeal.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public int updateByPrimaryKey(WeiboAppeal record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_weibo_appeal.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_weibo_appeal
     *
     * @ibatorgenerated Tue Apr 10 10:15:26 CST 2012
     */
    private static class UpdateByExampleParms extends WeiboAppealExample {
        private Object record;

        public UpdateByExampleParms(Object record, WeiboAppealExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}