package com.nali.spreader.dao.impl;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;
import com.nali.spreader.dao.ICrudUserTagDao;
import com.nali.spreader.data.UserTag;
import com.nali.spreader.data.UserTagExample;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

@Repository
public class CrudUserTagDao implements ICrudUserTagDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Sat Jul 30 16:58:55 CST 2011
     */
    public CrudUserTagDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public int countByExample(UserTagExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_user_tag.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public int deleteByExample(UserTagExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_user_tag.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        UserTag key = new UserTag();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_user_tag.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public void insert(UserTag record) {
        getSqlMapClientTemplate().insert("spreader_tb_user_tag.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public void insertSelective(UserTag record) {
        getSqlMapClientTemplate().insert("spreader_tb_user_tag.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<UserTag> selectByExample(UserTagExample example) {
        List<UserTag> list = getSqlMapClientTemplate().queryForList("spreader_tb_user_tag.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public UserTag selectByPrimaryKey(Long id) {
        UserTag key = new UserTag();
        key.setId(id);
        UserTag record = (UserTag) getSqlMapClientTemplate().queryForObject("spreader_tb_user_tag.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public int updateByExampleSelective(UserTag record, UserTagExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_user_tag.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public int updateByExample(UserTag record, UserTagExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_user_tag.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public int updateByPrimaryKeySelective(UserTag record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_user_tag.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public int updateByPrimaryKey(UserTag record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_user_tag.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_user_tag
     *
     * @ibatorgenerated Mon Apr 23 15:44:38 CST 2012
     */
    private static class UpdateByExampleParms extends UserTagExample {

        private Object record;

        public UpdateByExampleParms(Object record, UserTagExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
