package com.nali.spreader.model;

import java.io.Serializable;
import java.util.Date;

import com.nali.common.model.BaseModel;

public class RegularJob extends BaseModel implements Serializable {

    public static final Integer TRIGGER_TYPE_SIMPLE = 1;

    public static final Integer TRIGGER_TYPE_CRON = 2;

    private static final long serialVersionUID = 1340715782719822254L;

    public static class JobDto {
    	private String name;
    	private Object config;
    	private String description;
    	private Integer triggerType;
    	private String cron;
    	private Date start;
    	private int repeatTimes;
    	private int repeatInternal;
		public void setConfig(Object config) {
			this.config = config;
		}
		public void setTriggerType(Integer triggerType) {
			this.triggerType = triggerType;
		}
		public Object getConfig() {
			return config;
		}
		public Integer getTriggerType() {
			return triggerType;
		}
		public String getDescription() {
			return description;
		}
		public void setDescription(String description) {
			this.description = description;
		}
		public String getCron() {
			return cron;
		}
		public void setCron(String cron) {
			this.cron = cron;
		}
		public Date getStart() {
			return start;
		}
		public void setStart(Date start) {
			this.start = start;
		}
		public int getRepeatTimes() {
			return repeatTimes;
		}
		public void setRepeatTimes(int repeatTimes) {
			this.repeatTimes = repeatTimes;
		}
		public int getRepeatInternal() {
			return repeatInternal;
		}
		public void setRepeatInternal(int repeatInternal) {
			this.repeatInternal = repeatInternal;
		}
		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
    }
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_regular_job.id
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_regular_job.name
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_regular_job.trigger_type
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    private Integer triggerType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_regular_job.trigger_info
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    private String triggerInfo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_regular_job.description
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_regular_job.config
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    private String config;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_regular_job.id
     *
     * @return the value of spreader.tb_regular_job.id
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_regular_job.id
     *
     * @param id the value for spreader.tb_regular_job.id
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_regular_job.name
     *
     * @return the value of spreader.tb_regular_job.name
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_regular_job.name
     *
     * @param name the value for spreader.tb_regular_job.name
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_regular_job.trigger_type
     *
     * @return the value of spreader.tb_regular_job.trigger_type
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public Integer getTriggerType() {
        return triggerType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_regular_job.trigger_type
     *
     * @param triggerType the value for spreader.tb_regular_job.trigger_type
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public void setTriggerType(Integer triggerType) {
        this.triggerType = triggerType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_regular_job.trigger_info
     *
     * @return the value of spreader.tb_regular_job.trigger_info
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public String getTriggerInfo() {
        return triggerInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_regular_job.trigger_info
     *
     * @param triggerInfo the value for spreader.tb_regular_job.trigger_info
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public void setTriggerInfo(String triggerInfo) {
        this.triggerInfo = triggerInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_regular_job.description
     *
     * @return the value of spreader.tb_regular_job.description
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_regular_job.description
     *
     * @param description the value for spreader.tb_regular_job.description
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_regular_job.config
     *
     * @return the value of spreader.tb_regular_job.config
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_regular_job.config
     *
     * @param config the value for spreader.tb_regular_job.config
     *
     * @ibatorgenerated Sat Nov 12 19:07:08 CST 2011
     */
    public void setConfig(String config) {
        this.config = config;
    }
}
