use spreader_qtz_czy;
delete from QRTZ_SIMPLE_TRIGGERS;
delete from QRTZ_CRON_TRIGGERS;
delete from QRTZ_TRIGGERS;
delete from QRTZ_JOB_LISTENERS;
delete from QRTZ_TRIGGER_LISTENERS;
delete from QRTZ_FIRED_TRIGGERS;
delete from QRTZ_PAUSED_TRIGGER_GRPS;
delete from QRTZ_SCHEDULER_STATE;
delete from QRTZ_LOCKS;
delete from QRTZ_BLOB_TRIGGERS;
delete from QRTZ_JOB_DETAILS;
delete from QRTZ_CALENDARS;
delete from LTS_TRIGGER_EXECUTION_MSG;
delete from LTS_TRIGGER_EXECUTION_RECORD;
delete from LTS_AGENT_EXECUTION_MSG;