package com.nali.spreader.data;

import com.nali.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class Career extends BaseModel implements Serializable {

    private static final long serialVersionUID = 6578908393585266887L;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_career.id
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_career.uid
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    private Long uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_career.company
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    private String company;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_career.province
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    private String province;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_career.city
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    private String city;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_career.start_date
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    private Date startDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_career.end_date
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    private Date endDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_career.position
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    private String position;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_career.id
     *
     * @return the value of spreader.tb_career.id
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_career.id
     *
     * @param id the value for spreader.tb_career.id
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_career.uid
     *
     * @return the value of spreader.tb_career.uid
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_career.uid
     *
     * @param uid the value for spreader.tb_career.uid
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_career.company
     *
     * @return the value of spreader.tb_career.company
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_career.company
     *
     * @param company the value for spreader.tb_career.company
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_career.province
     *
     * @return the value of spreader.tb_career.province
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_career.province
     *
     * @param province the value for spreader.tb_career.province
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_career.city
     *
     * @return the value of spreader.tb_career.city
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_career.city
     *
     * @param city the value for spreader.tb_career.city
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_career.start_date
     *
     * @return the value of spreader.tb_career.start_date
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_career.start_date
     *
     * @param startDate the value for spreader.tb_career.start_date
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_career.end_date
     *
     * @return the value of spreader.tb_career.end_date
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_career.end_date
     *
     * @param endDate the value for spreader.tb_career.end_date
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_career.position
     *
     * @return the value of spreader.tb_career.position
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_career.position
     *
     * @param position the value for spreader.tb_career.position
     *
     * @ibatorgenerated Thu Aug 04 10:00:33 CST 2011
     */
    public void setPosition(String position) {
        this.position = position;
    }
}
