package com.nali.spreader.data;

import com.nali.common.model.BaseModel;
import java.io.Serializable;

public class UserRelation extends BaseModel implements Serializable {

    private static final long serialVersionUID = 3637913791620722409L;

    public static final Integer TYPE_ATTENTION = 1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_relation.to_uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    private Long toUid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_relation.type
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_relation.uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    private Long uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_relation.website_id
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    private Integer websiteId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_relation.website_uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    private Long websiteUid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_relation.to_website_uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    private Long toWebsiteUid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_relation.is_robot_user
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    private Boolean isRobotUser;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_relation.to_uid
     *
     * @return the value of spreader.tb_user_relation.to_uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public Long getToUid() {
        return toUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_relation.to_uid
     *
     * @param toUid the value for spreader.tb_user_relation.to_uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public void setToUid(Long toUid) {
        this.toUid = toUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_relation.type
     *
     * @return the value of spreader.tb_user_relation.type
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_relation.type
     *
     * @param type the value for spreader.tb_user_relation.type
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_relation.uid
     *
     * @return the value of spreader.tb_user_relation.uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_relation.uid
     *
     * @param uid the value for spreader.tb_user_relation.uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_relation.website_id
     *
     * @return the value of spreader.tb_user_relation.website_id
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_relation.website_id
     *
     * @param websiteId the value for spreader.tb_user_relation.website_id
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_relation.website_uid
     *
     * @return the value of spreader.tb_user_relation.website_uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public Long getWebsiteUid() {
        return websiteUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_relation.website_uid
     *
     * @param websiteUid the value for spreader.tb_user_relation.website_uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public void setWebsiteUid(Long websiteUid) {
        this.websiteUid = websiteUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_relation.to_website_uid
     *
     * @return the value of spreader.tb_user_relation.to_website_uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public Long getToWebsiteUid() {
        return toWebsiteUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_relation.to_website_uid
     *
     * @param toWebsiteUid the value for spreader.tb_user_relation.to_website_uid
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public void setToWebsiteUid(Long toWebsiteUid) {
        this.toWebsiteUid = toWebsiteUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_relation.is_robot_user
     *
     * @return the value of spreader.tb_user_relation.is_robot_user
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public Boolean getIsRobotUser() {
        return isRobotUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_relation.is_robot_user
     *
     * @param isRobotUser the value for spreader.tb_user_relation.is_robot_user
     *
     * @ibatorgenerated Tue Nov 22 15:00:05 CST 2011
     */
    public void setIsRobotUser(Boolean isRobotUser) {
        this.isRobotUser = isRobotUser;
    }
}
