package com.nali.spreader.model;

import com.nali.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class ClientError extends BaseModel implements Serializable {

    private static final long serialVersionUID = 666293492477279965L;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.task_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private Long taskId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.client_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private Long clientId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.task_code
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private String taskCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.error_code
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private String errorCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.error_time
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private Date errorTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.website_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private Integer websiteId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.uid
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private Long uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.website_error_code
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private String websiteErrorCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.website_error_desc
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private String websiteErrorDesc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.referer_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private Long refererId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_error.error_desc
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    private String errorDesc;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.task_id
     *
     * @return the value of spreader.tb_client_error.task_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.task_id
     *
     * @param taskId the value for spreader.tb_client_error.task_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.client_id
     *
     * @return the value of spreader.tb_client_error.client_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.client_id
     *
     * @param clientId the value for spreader.tb_client_error.client_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.task_code
     *
     * @return the value of spreader.tb_client_error.task_code
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.task_code
     *
     * @param taskCode the value for spreader.tb_client_error.task_code
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.error_code
     *
     * @return the value of spreader.tb_client_error.error_code
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.error_code
     *
     * @param errorCode the value for spreader.tb_client_error.error_code
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.error_time
     *
     * @return the value of spreader.tb_client_error.error_time
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public Date getErrorTime() {
        return errorTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.error_time
     *
     * @param errorTime the value for spreader.tb_client_error.error_time
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setErrorTime(Date errorTime) {
        this.errorTime = errorTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.website_id
     *
     * @return the value of spreader.tb_client_error.website_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.website_id
     *
     * @param websiteId the value for spreader.tb_client_error.website_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.uid
     *
     * @return the value of spreader.tb_client_error.uid
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.uid
     *
     * @param uid the value for spreader.tb_client_error.uid
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.website_error_code
     *
     * @return the value of spreader.tb_client_error.website_error_code
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public String getWebsiteErrorCode() {
        return websiteErrorCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.website_error_code
     *
     * @param websiteErrorCode the value for spreader.tb_client_error.website_error_code
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setWebsiteErrorCode(String websiteErrorCode) {
        this.websiteErrorCode = websiteErrorCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.website_error_desc
     *
     * @return the value of spreader.tb_client_error.website_error_desc
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public String getWebsiteErrorDesc() {
        return websiteErrorDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.website_error_desc
     *
     * @param websiteErrorDesc the value for spreader.tb_client_error.website_error_desc
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setWebsiteErrorDesc(String websiteErrorDesc) {
        this.websiteErrorDesc = websiteErrorDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.referer_id
     *
     * @return the value of spreader.tb_client_error.referer_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public Long getRefererId() {
        return refererId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.referer_id
     *
     * @param refererId the value for spreader.tb_client_error.referer_id
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setRefererId(Long refererId) {
        this.refererId = refererId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_error.error_desc
     *
     * @return the value of spreader.tb_client_error.error_desc
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public String getErrorDesc() {
        return errorDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_error.error_desc
     *
     * @param errorDesc the value for spreader.tb_client_error.error_desc
     *
     * @ibatorgenerated Fri Mar 30 16:48:07 CST 2012
     */
    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc;
    }
}
