package com.nali.spreader.model;

import com.nali.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class ClientReport extends BaseModel implements Serializable {

    private static final long serialVersionUID = -7153009890016651768L;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.client_id
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private Long clientId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.client_seq
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private Long clientSeq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.task_date
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private Date taskDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.task_type
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private Integer taskType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.update_time
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.create_time
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.expect_count
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private Integer expectCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.actual_count
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private Integer actualCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.action_id
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private Long actionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.app_name
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private String appName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_report.success_count
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    private Integer successCount;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.client_id
     *
     * @return the value of spreader.tb_client_report.client_id
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.client_id
     *
     * @param clientId the value for spreader.tb_client_report.client_id
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.client_seq
     *
     * @return the value of spreader.tb_client_report.client_seq
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public Long getClientSeq() {
        return clientSeq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.client_seq
     *
     * @param clientSeq the value for spreader.tb_client_report.client_seq
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setClientSeq(Long clientSeq) {
        this.clientSeq = clientSeq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.task_date
     *
     * @return the value of spreader.tb_client_report.task_date
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public Date getTaskDate() {
        return taskDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.task_date
     *
     * @param taskDate the value for spreader.tb_client_report.task_date
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setTaskDate(Date taskDate) {
        this.taskDate = taskDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.task_type
     *
     * @return the value of spreader.tb_client_report.task_type
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.task_type
     *
     * @param taskType the value for spreader.tb_client_report.task_type
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.update_time
     *
     * @return the value of spreader.tb_client_report.update_time
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.update_time
     *
     * @param updateTime the value for spreader.tb_client_report.update_time
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.create_time
     *
     * @return the value of spreader.tb_client_report.create_time
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.create_time
     *
     * @param createTime the value for spreader.tb_client_report.create_time
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.expect_count
     *
     * @return the value of spreader.tb_client_report.expect_count
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public Integer getExpectCount() {
        return expectCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.expect_count
     *
     * @param expectCount the value for spreader.tb_client_report.expect_count
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setExpectCount(Integer expectCount) {
        this.expectCount = expectCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.actual_count
     *
     * @return the value of spreader.tb_client_report.actual_count
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public Integer getActualCount() {
        return actualCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.actual_count
     *
     * @param actualCount the value for spreader.tb_client_report.actual_count
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setActualCount(Integer actualCount) {
        this.actualCount = actualCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.action_id
     *
     * @return the value of spreader.tb_client_report.action_id
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public Long getActionId() {
        return actionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.action_id
     *
     * @param actionId the value for spreader.tb_client_report.action_id
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setActionId(Long actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.app_name
     *
     * @return the value of spreader.tb_client_report.app_name
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.app_name
     *
     * @param appName the value for spreader.tb_client_report.app_name
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_report.success_count
     *
     * @return the value of spreader.tb_client_report.success_count
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public Integer getSuccessCount() {
        return successCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_report.success_count
     *
     * @param successCount the value for spreader.tb_client_report.success_count
     *
     * @ibatorgenerated Thu Jul 25 13:47:02 CST 2013
     */
    public void setSuccessCount(Integer successCount) {
        this.successCount = successCount;
    }

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ClientReport [clientId=");
		builder.append(clientId);
		builder.append(", clientSeq=");
		builder.append(clientSeq);
		builder.append(", taskDate=");
		builder.append(taskDate);
		builder.append(", taskType=");
		builder.append(taskType);
		builder.append(", updateTime=");
		builder.append(updateTime);
		builder.append(", createTime=");
		builder.append(createTime);
		builder.append(", expectCount=");
		builder.append(expectCount);
		builder.append(", actualCount=");
		builder.append(actualCount);
		builder.append(", actionId=");
		builder.append(actionId);
		builder.append(", appName=");
		builder.append(appName);
		builder.append(", successCount=");
		builder.append(successCount);
		builder.append("]");
		return builder.toString();
	}
}
