package com.nali.spreader.model;

import com.nali.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class ClientTaskLog extends BaseModel implements Serializable {
    private static final long serialVersionUID = -4576591535818099466L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task_log.task_id
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    private Long taskId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task_log.client_id
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    private Long clientId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task_log.task_code
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    private String taskCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task_log.status
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task_log.executed_time
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    private Date executedTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task_log.error_code
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    private String errorCode;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task_log.task_id
     *
     * @return the value of spreader.tb_client_task_log.task_id
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task_log.task_id
     *
     * @param taskId the value for spreader.tb_client_task_log.task_id
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task_log.client_id
     *
     * @return the value of spreader.tb_client_task_log.client_id
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task_log.client_id
     *
     * @param clientId the value for spreader.tb_client_task_log.client_id
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task_log.task_code
     *
     * @return the value of spreader.tb_client_task_log.task_code
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task_log.task_code
     *
     * @param taskCode the value for spreader.tb_client_task_log.task_code
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task_log.status
     *
     * @return the value of spreader.tb_client_task_log.status
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task_log.status
     *
     * @param status the value for spreader.tb_client_task_log.status
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task_log.executed_time
     *
     * @return the value of spreader.tb_client_task_log.executed_time
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public Date getExecutedTime() {
        return executedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task_log.executed_time
     *
     * @param executedTime the value for spreader.tb_client_task_log.executed_time
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public void setExecutedTime(Date executedTime) {
        this.executedTime = executedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task_log.error_code
     *
     * @return the value of spreader.tb_client_task_log.error_code
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task_log.error_code
     *
     * @param errorCode the value for spreader.tb_client_task_log.error_code
     *
     * @ibatorgenerated Wed Jan 11 14:57:16 CST 2012
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }
}