package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudUserDao;
import com.nali.spreader.model.User;
import com.nali.spreader.model.UserExample;

@Repository
public class CrudUserDao implements ICrudUserDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:16:22 CST 2011
     */
    public CrudUserDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int countByExample(UserExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_user.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int deleteByExample(UserExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        User key = new User();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_user.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public void insert(User record) {
        getSqlMapClientTemplate().insert("spreader_tb_user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public void insertSelective(User record) {
        getSqlMapClientTemplate().insert("spreader_tb_user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<User> selectByExample(UserExample example) {
        List<User> list = getSqlMapClientTemplate().queryForList("spreader_tb_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public User selectByPrimaryKey(Integer id) {
        User key = new User();
        key.setId(id);
        User record = (User) getSqlMapClientTemplate().queryForObject("spreader_tb_user.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int updateByExampleSelective(User record, UserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int updateByExample(User record, UserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int updateByPrimaryKeySelective(User record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int updateByPrimaryKey(User record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_user
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    private static class UpdateByExampleParms extends UserExample {

        private Object record;

        public UpdateByExampleParms(Object record, UserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
