package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudContentCategoryDao;
import com.nali.spreader.model.ContentCategory;
import com.nali.spreader.model.ContentCategoryExample;

@Repository
public class CrudContentCategoryDao implements ICrudContentCategoryDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public CrudContentCategoryDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int countByExample(ContentCategoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_content_category.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int deleteByExample(ContentCategoryExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_content_category.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int deleteByPrimaryKey(Long cid, Long contentId) {
        ContentCategory key = new ContentCategory();
        key.setCid(cid);
        key.setContentId(contentId);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_content_category.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public void insert(ContentCategory record) {
        getSqlMapClientTemplate().insert("spreader_tb_content_category.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public void insertSelective(ContentCategory record) {
        getSqlMapClientTemplate().insert("spreader_tb_content_category.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<ContentCategory> selectByExample(ContentCategoryExample example) {
        List<ContentCategory> list = getSqlMapClientTemplate().queryForList("spreader_tb_content_category.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int updateByExampleSelective(ContentCategory record, ContentCategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_content_category.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int updateByExample(ContentCategory record, ContentCategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_content_category.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_content_category
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    private static class UpdateByExampleParms extends ContentCategoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, ContentCategoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}