package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudUserCategoryDao;
import com.nali.spreader.model.TbUserCategoryKey;
import com.nali.spreader.model.UserCategoryExample;

@Repository
public class CrudUserCategoryDao implements ICrudUserCategoryDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:16:22 CST 2011
     */
    public CrudUserCategoryDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int countByExample(UserCategoryExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_user_category.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int deleteByExample(UserCategoryExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_user_category.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int deleteByPrimaryKey(TbUserCategoryKey key) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_user_category.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public void insert(TbUserCategoryKey record) {
        getSqlMapClientTemplate().insert("spreader_tb_user_category.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public void insertSelective(TbUserCategoryKey record) {
        getSqlMapClientTemplate().insert("spreader_tb_user_category.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<TbUserCategoryKey> selectByExample(UserCategoryExample example) {
        List<TbUserCategoryKey> list = getSqlMapClientTemplate().queryForList("spreader_tb_user_category.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int updateByExampleSelective(TbUserCategoryKey record, UserCategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_user_category.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int updateByExample(TbUserCategoryKey record, UserCategoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_user_category.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_user_category
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    private static class UpdateByExampleParms extends UserCategoryExample {

        private Object record;

        public UpdateByExampleParms(Object record, UserCategoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
