package com.nali.spreader.model;

import com.nali.common.model.BaseModel;

public class TbUserCategoryKey extends BaseModel {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_category.cid
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    private Long cid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_category.uid
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    private Long uid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_category.cid
     *
     * @return the value of spreader.tb_user_category.cid
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_category.cid
     *
     * @param cid the value for spreader.tb_user_category.cid
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_category.uid
     *
     * @return the value of spreader.tb_user_category.uid
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_category.uid
     *
     * @param uid the value for spreader.tb_user_category.uid
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}