package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudTaskTypeDao;
import com.nali.spreader.model.TaskType;
import com.nali.spreader.model.TaskTypeExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudTaskTypeDao implements ICrudTaskTypeDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Thu Mar 31 15:39:16 CST 2011
     */
    public CrudTaskTypeDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public int countByExample(TaskTypeExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_task_type.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public int deleteByExample(TaskTypeExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_task_type.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public int deleteByPrimaryKey(Integer taskType) {
        TaskType key = new TaskType();
        key.setTaskType(taskType);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_task_type.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public void insert(TaskType record) {
        getSqlMapClientTemplate().insert("spreader_tb_task_type.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public void insertSelective(TaskType record) {
        getSqlMapClientTemplate().insert("spreader_tb_task_type.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public List selectByExample(TaskTypeExample example) {
        List list = getSqlMapClientTemplate().queryForList("spreader_tb_task_type.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public TaskType selectByPrimaryKey(Integer taskType) {
        TaskType key = new TaskType();
        key.setTaskType(taskType);
        TaskType record = (TaskType) getSqlMapClientTemplate().queryForObject("spreader_tb_task_type.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public int updateByExampleSelective(TaskType record, TaskTypeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_task_type.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public int updateByExample(TaskType record, TaskTypeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_task_type.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public int updateByPrimaryKeySelective(TaskType record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_task_type.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public int updateByPrimaryKey(TaskType record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_task_type.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    private static class UpdateByExampleParms extends TaskTypeExample {

        private Object record;

        public UpdateByExampleParms(Object record, TaskTypeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
