package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudClientDao;
import com.nali.spreader.model.Client;
import com.nali.spreader.model.ClientExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudClientDao implements ICrudClientDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public CrudClientDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int countByExample(ClientExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_client.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int deleteByExample(ClientExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_client.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        Client key = new Client();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_client.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void insert(Client record) {
        getSqlMapClientTemplate().insert("spreader_tb_client.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void insertSelective(Client record) {
        getSqlMapClientTemplate().insert("spreader_tb_client.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public List selectByExample(ClientExample example) {
        List list = getSqlMapClientTemplate().queryForList("spreader_tb_client.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Client selectByPrimaryKey(Integer id) {
        Client key = new Client();
        key.setId(id);
        Client record = (Client) getSqlMapClientTemplate().queryForObject("spreader_tb_client.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByExampleSelective(Client record, ClientExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_client.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByExample(Client record, ClientExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_client.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByPrimaryKeySelective(Client record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_client.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByPrimaryKey(Client record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_client.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private static class UpdateByExampleParms extends ClientExample {

        private Object record;

        public UpdateByExampleParms(Object record, ClientExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
