package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudAdminDao;
import com.nali.spreader.model.Admin;
import com.nali.spreader.model.AdminExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudAdminDao implements ICrudAdminDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public CrudAdminDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int countByExample(AdminExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_admin.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int deleteByExample(AdminExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_admin.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        Admin key = new Admin();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_admin.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void insert(Admin record) {
        getSqlMapClientTemplate().insert("spreader_tb_admin.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void insertSelective(Admin record) {
        getSqlMapClientTemplate().insert("spreader_tb_admin.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public List selectByExample(AdminExample example) {
        List list = getSqlMapClientTemplate().queryForList("spreader_tb_admin.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Admin selectByPrimaryKey(Integer id) {
        Admin key = new Admin();
        key.setId(id);
        Admin record = (Admin) getSqlMapClientTemplate().queryForObject("spreader_tb_admin.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByExampleSelective(Admin record, AdminExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_admin.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByExample(Admin record, AdminExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_admin.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByPrimaryKeySelective(Admin record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_admin.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByPrimaryKey(Admin record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_admin.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_admin
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private static class UpdateByExampleParms extends AdminExample {

        private Object record;

        public UpdateByExampleParms(Object record, AdminExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
