package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudTaskDao;
import com.nali.spreader.model.Task;
import com.nali.spreader.model.TaskExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudTaskDao implements ICrudTaskDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public CrudTaskDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int countByExample(TaskExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_task.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int deleteByExample(TaskExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_task.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int deleteByPrimaryKey(Long id) {
        Task key = new Task();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_task.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public void insert(Task record) {
        getSqlMapClientTemplate().insert("spreader_tb_task.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public void insertSelective(Task record) {
        getSqlMapClientTemplate().insert("spreader_tb_task.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public List selectByExampleWithBLOBs(TaskExample example) {
        List list = getSqlMapClientTemplate().queryForList("spreader_tb_task.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public List selectByExampleWithoutBLOBs(TaskExample example) {
        List list = getSqlMapClientTemplate().queryForList("spreader_tb_task.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public Task selectByPrimaryKey(Long id) {
        Task key = new Task();
        key.setId(id);
        Task record = (Task) getSqlMapClientTemplate().queryForObject("spreader_tb_task.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int updateByExampleSelective(Task record, TaskExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_task.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int updateByExampleWithBLOBs(Task record, TaskExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_task.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int updateByExampleWithoutBLOBs(Task record, TaskExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_task.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int updateByPrimaryKeySelective(Task record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_task.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int updateByPrimaryKeyWithBLOBs(Task record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_task.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int updateByPrimaryKeyWithoutBLOBs(Task record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_task.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    private static class UpdateByExampleParms extends TaskExample {
        private Object record;

        public UpdateByExampleParms(Object record, TaskExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}