package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudTargetHeadersDao;
import com.nali.spreader.model.TargetHeaders;
import com.nali.spreader.model.TargetHeadersExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudTargetHeadersDao implements ICrudTargetHeadersDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Sun Mar 13 15:40:28 CST 2011
     */
    public CrudTargetHeadersDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int countByExample(TargetHeadersExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_target_headers.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int deleteByExample(TargetHeadersExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_target_headers.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int deleteByPrimaryKey(Long id) {
        TargetHeaders key = new TargetHeaders();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_target_headers.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void insert(TargetHeaders record) {
        getSqlMapClientTemplate().insert("spreader_tb_target_headers.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void insertSelective(TargetHeaders record) {
        getSqlMapClientTemplate().insert("spreader_tb_target_headers.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public List selectByExample(TargetHeadersExample example) {
        List list = getSqlMapClientTemplate().queryForList("spreader_tb_target_headers.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public TargetHeaders selectByPrimaryKey(Long id) {
        TargetHeaders key = new TargetHeaders();
        key.setId(id);
        TargetHeaders record = (TargetHeaders) getSqlMapClientTemplate().queryForObject("spreader_tb_target_headers.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByExampleSelective(TargetHeaders record, TargetHeadersExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_target_headers.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByExample(TargetHeaders record, TargetHeadersExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_target_headers.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByPrimaryKeySelective(TargetHeaders record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_target_headers.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public int updateByPrimaryKey(TargetHeaders record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_target_headers.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_target_headers
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private static class UpdateByExampleParms extends TargetHeadersExample {

        private Object record;

        public UpdateByExampleParms(Object record, TargetHeadersExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
