package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudRobotUserDao;
import com.nali.spreader.model.RobotUser;
import com.nali.spreader.model.RobotUserExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudRobotUserDao implements ICrudRobotUserDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public CrudRobotUserDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int countByExample(RobotUserExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_robot_user.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int deleteByExample(RobotUserExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_robot_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int deleteByPrimaryKey(Long uid) {
        RobotUser key = new RobotUser();
        key.setUid(uid);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_robot_user.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public void insert(RobotUser record) {
        getSqlMapClientTemplate().insert("spreader_tb_robot_user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public void insertSelective(RobotUser record) {
        getSqlMapClientTemplate().insert("spreader_tb_robot_user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public List selectByExample(RobotUserExample example) {
        List list = getSqlMapClientTemplate().queryForList("spreader_tb_robot_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public RobotUser selectByPrimaryKey(Long uid) {
        RobotUser key = new RobotUser();
        key.setUid(uid);
        RobotUser record = (RobotUser) getSqlMapClientTemplate().queryForObject("spreader_tb_robot_user.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int updateByExampleSelective(RobotUser record, RobotUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int updateByExample(RobotUser record, RobotUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int updateByPrimaryKeySelective(RobotUser record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public int updateByPrimaryKey(RobotUser record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_robot_user
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    private static class UpdateByExampleParms extends RobotUserExample {
        private Object record;

        public UpdateByExampleParms(Object record, RobotUserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}