package com.nali.spreader.dao;

import com.nali.spreader.model.Client;
import com.nali.spreader.model.ClientExample;
import java.util.List;

public interface ICrudClientDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    int countByExample(ClientExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    int deleteByExample(ClientExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    void insert(Client record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    void insertSelective(Client record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    List selectByExample(ClientExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    Client selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    int updateByExampleSelective(Client record, ClientExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    int updateByExample(Client record, ClientExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    int updateByPrimaryKeySelective(Client record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    int updateByPrimaryKey(Client record);
}
