package com.nali.spreader.dao;

import com.nali.spreader.model.RealUser;
import com.nali.spreader.model.RealUserExample;
import java.util.List;

public interface ICrudRealUserDao {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    int countByExample(RealUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    int deleteByExample(RealUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    void insert(RealUser record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    void insertSelective(RealUser record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    List selectByExample(RealUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    RealUser selectByPrimaryKey(Long uid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    int updateByExampleSelective(RealUser record, RealUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    int updateByExample(RealUser record, RealUserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    int updateByPrimaryKeySelective(RealUser record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    int updateByPrimaryKey(RealUser record);
}