package com.nali.spreader.data;

import com.nali.common.model.Limit;
import com.nali.common.model.Shard;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Date;

public class AppUdidExample {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Wed Jun 06 17:41:16 CST 2012
     */
    public AppUdidExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Wed Jun 06 17:41:16 CST 2012
     */
    protected AppUdidExample(AppUdidExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.limit = example.limit;
        this.shard = example.shard;
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    private Shard shard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    private Limit limit;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    public void setShard(Shard shard) {
        this.shard = shard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    public void setLimit(Limit limit) {
        this.limit = limit;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Apr 08 16:58:06 CST 2013
     */
    public static class Criteria {

        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andRegisterIdIsNull() {
            addCriterion("register_id is null");
            return this;
        }

        public Criteria andRegisterIdIsNotNull() {
            addCriterion("register_id is not null");
            return this;
        }

        public Criteria andRegisterIdEqualTo(Long value) {
            addCriterion("register_id =", value, "registerId");
            return this;
        }

        public Criteria andRegisterIdNotEqualTo(Long value) {
            addCriterion("register_id <>", value, "registerId");
            return this;
        }

        public Criteria andRegisterIdGreaterThan(Long value) {
            addCriterion("register_id >", value, "registerId");
            return this;
        }

        public Criteria andRegisterIdGreaterThanOrEqualTo(Long value) {
            addCriterion("register_id >=", value, "registerId");
            return this;
        }

        public Criteria andRegisterIdLessThan(Long value) {
            addCriterion("register_id <", value, "registerId");
            return this;
        }

        public Criteria andRegisterIdLessThanOrEqualTo(Long value) {
            addCriterion("register_id <=", value, "registerId");
            return this;
        }

        public Criteria andRegisterIdIn(List<Long> values) {
            addCriterion("register_id in", values, "registerId");
            return this;
        }

        public Criteria andRegisterIdNotIn(List<Long> values) {
            addCriterion("register_id not in", values, "registerId");
            return this;
        }

        public Criteria andRegisterIdBetween(Long value1, Long value2) {
            addCriterion("register_id between", value1, value2, "registerId");
            return this;
        }

        public Criteria andRegisterIdNotBetween(Long value1, Long value2) {
            addCriterion("register_id not between", value1, value2, "registerId");
            return this;
        }

        public Criteria andUdidIsNull() {
            addCriterion("udid is null");
            return this;
        }

        public Criteria andUdidIsNotNull() {
            addCriterion("udid is not null");
            return this;
        }

        public Criteria andUdidEqualTo(String value) {
            addCriterion("udid =", value, "udid");
            return this;
        }

        public Criteria andUdidNotEqualTo(String value) {
            addCriterion("udid <>", value, "udid");
            return this;
        }

        public Criteria andUdidGreaterThan(String value) {
            addCriterion("udid >", value, "udid");
            return this;
        }

        public Criteria andUdidGreaterThanOrEqualTo(String value) {
            addCriterion("udid >=", value, "udid");
            return this;
        }

        public Criteria andUdidLessThan(String value) {
            addCriterion("udid <", value, "udid");
            return this;
        }

        public Criteria andUdidLessThanOrEqualTo(String value) {
            addCriterion("udid <=", value, "udid");
            return this;
        }

        public Criteria andUdidLike(String value) {
            addCriterion("udid like", value, "udid");
            return this;
        }

        public Criteria andUdidNotLike(String value) {
            addCriterion("udid not like", value, "udid");
            return this;
        }

        public Criteria andUdidIn(List<String> values) {
            addCriterion("udid in", values, "udid");
            return this;
        }

        public Criteria andUdidNotIn(List<String> values) {
            addCriterion("udid not in", values, "udid");
            return this;
        }

        public Criteria andUdidBetween(String value1, String value2) {
            addCriterion("udid between", value1, value2, "udid");
            return this;
        }

        public Criteria andUdidNotBetween(String value1, String value2) {
            addCriterion("udid not between", value1, value2, "udid");
            return this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("pwd is null");
            return this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("pwd is not null");
            return this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("pwd =", value, "pwd");
            return this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("pwd <>", value, "pwd");
            return this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("pwd >", value, "pwd");
            return this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("pwd >=", value, "pwd");
            return this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("pwd <", value, "pwd");
            return this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("pwd <=", value, "pwd");
            return this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("pwd like", value, "pwd");
            return this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("pwd not like", value, "pwd");
            return this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("pwd in", values, "pwd");
            return this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("pwd not in", values, "pwd");
            return this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("pwd between", value1, value2, "pwd");
            return this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("pwd not between", value1, value2, "pwd");
            return this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andIpadSerialIsNull() {
            addCriterion("ipad_serial is null");
            return this;
        }

        public Criteria andIpadSerialIsNotNull() {
            addCriterion("ipad_serial is not null");
            return this;
        }

        public Criteria andIpadSerialEqualTo(String value) {
            addCriterion("ipad_serial =", value, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialNotEqualTo(String value) {
            addCriterion("ipad_serial <>", value, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialGreaterThan(String value) {
            addCriterion("ipad_serial >", value, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialGreaterThanOrEqualTo(String value) {
            addCriterion("ipad_serial >=", value, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialLessThan(String value) {
            addCriterion("ipad_serial <", value, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialLessThanOrEqualTo(String value) {
            addCriterion("ipad_serial <=", value, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialLike(String value) {
            addCriterion("ipad_serial like", value, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialNotLike(String value) {
            addCriterion("ipad_serial not like", value, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialIn(List<String> values) {
            addCriterion("ipad_serial in", values, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialNotIn(List<String> values) {
            addCriterion("ipad_serial not in", values, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialBetween(String value1, String value2) {
            addCriterion("ipad_serial between", value1, value2, "ipadSerial");
            return this;
        }

        public Criteria andIpadSerialNotBetween(String value1, String value2) {
            addCriterion("ipad_serial not between", value1, value2, "ipadSerial");
            return this;
        }

        public Criteria andIphoneSerialIsNull() {
            addCriterion("iphone_serial is null");
            return this;
        }

        public Criteria andIphoneSerialIsNotNull() {
            addCriterion("iphone_serial is not null");
            return this;
        }

        public Criteria andIphoneSerialEqualTo(String value) {
            addCriterion("iphone_serial =", value, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialNotEqualTo(String value) {
            addCriterion("iphone_serial <>", value, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialGreaterThan(String value) {
            addCriterion("iphone_serial >", value, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialGreaterThanOrEqualTo(String value) {
            addCriterion("iphone_serial >=", value, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialLessThan(String value) {
            addCriterion("iphone_serial <", value, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialLessThanOrEqualTo(String value) {
            addCriterion("iphone_serial <=", value, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialLike(String value) {
            addCriterion("iphone_serial like", value, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialNotLike(String value) {
            addCriterion("iphone_serial not like", value, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialIn(List<String> values) {
            addCriterion("iphone_serial in", values, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialNotIn(List<String> values) {
            addCriterion("iphone_serial not in", values, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialBetween(String value1, String value2) {
            addCriterion("iphone_serial between", value1, value2, "iphoneSerial");
            return this;
        }

        public Criteria andIphoneSerialNotBetween(String value1, String value2) {
            addCriterion("iphone_serial not between", value1, value2, "iphoneSerial");
            return this;
        }

        public Criteria andImeiIsNull() {
            addCriterion("imei is null");
            return this;
        }

        public Criteria andImeiIsNotNull() {
            addCriterion("imei is not null");
            return this;
        }

        public Criteria andImeiEqualTo(String value) {
            addCriterion("imei =", value, "imei");
            return this;
        }

        public Criteria andImeiNotEqualTo(String value) {
            addCriterion("imei <>", value, "imei");
            return this;
        }

        public Criteria andImeiGreaterThan(String value) {
            addCriterion("imei >", value, "imei");
            return this;
        }

        public Criteria andImeiGreaterThanOrEqualTo(String value) {
            addCriterion("imei >=", value, "imei");
            return this;
        }

        public Criteria andImeiLessThan(String value) {
            addCriterion("imei <", value, "imei");
            return this;
        }

        public Criteria andImeiLessThanOrEqualTo(String value) {
            addCriterion("imei <=", value, "imei");
            return this;
        }

        public Criteria andImeiLike(String value) {
            addCriterion("imei like", value, "imei");
            return this;
        }

        public Criteria andImeiNotLike(String value) {
            addCriterion("imei not like", value, "imei");
            return this;
        }

        public Criteria andImeiIn(List<String> values) {
            addCriterion("imei in", values, "imei");
            return this;
        }

        public Criteria andImeiNotIn(List<String> values) {
            addCriterion("imei not in", values, "imei");
            return this;
        }

        public Criteria andImeiBetween(String value1, String value2) {
            addCriterion("imei between", value1, value2, "imei");
            return this;
        }

        public Criteria andImeiNotBetween(String value1, String value2) {
            addCriterion("imei not between", value1, value2, "imei");
            return this;
        }

        public Criteria andImsiIsNull() {
            addCriterion("imsi is null");
            return this;
        }

        public Criteria andImsiIsNotNull() {
            addCriterion("imsi is not null");
            return this;
        }

        public Criteria andImsiEqualTo(String value) {
            addCriterion("imsi =", value, "imsi");
            return this;
        }

        public Criteria andImsiNotEqualTo(String value) {
            addCriterion("imsi <>", value, "imsi");
            return this;
        }

        public Criteria andImsiGreaterThan(String value) {
            addCriterion("imsi >", value, "imsi");
            return this;
        }

        public Criteria andImsiGreaterThanOrEqualTo(String value) {
            addCriterion("imsi >=", value, "imsi");
            return this;
        }

        public Criteria andImsiLessThan(String value) {
            addCriterion("imsi <", value, "imsi");
            return this;
        }

        public Criteria andImsiLessThanOrEqualTo(String value) {
            addCriterion("imsi <=", value, "imsi");
            return this;
        }

        public Criteria andImsiLike(String value) {
            addCriterion("imsi like", value, "imsi");
            return this;
        }

        public Criteria andImsiNotLike(String value) {
            addCriterion("imsi not like", value, "imsi");
            return this;
        }

        public Criteria andImsiIn(List<String> values) {
            addCriterion("imsi in", values, "imsi");
            return this;
        }

        public Criteria andImsiNotIn(List<String> values) {
            addCriterion("imsi not in", values, "imsi");
            return this;
        }

        public Criteria andImsiBetween(String value1, String value2) {
            addCriterion("imsi between", value1, value2, "imsi");
            return this;
        }

        public Criteria andImsiNotBetween(String value1, String value2) {
            addCriterion("imsi not between", value1, value2, "imsi");
            return this;
        }

        public Criteria andIccidIsNull() {
            addCriterion("iccid is null");
            return this;
        }

        public Criteria andIccidIsNotNull() {
            addCriterion("iccid is not null");
            return this;
        }

        public Criteria andIccidEqualTo(String value) {
            addCriterion("iccid =", value, "iccid");
            return this;
        }

        public Criteria andIccidNotEqualTo(String value) {
            addCriterion("iccid <>", value, "iccid");
            return this;
        }

        public Criteria andIccidGreaterThan(String value) {
            addCriterion("iccid >", value, "iccid");
            return this;
        }

        public Criteria andIccidGreaterThanOrEqualTo(String value) {
            addCriterion("iccid >=", value, "iccid");
            return this;
        }

        public Criteria andIccidLessThan(String value) {
            addCriterion("iccid <", value, "iccid");
            return this;
        }

        public Criteria andIccidLessThanOrEqualTo(String value) {
            addCriterion("iccid <=", value, "iccid");
            return this;
        }

        public Criteria andIccidLike(String value) {
            addCriterion("iccid like", value, "iccid");
            return this;
        }

        public Criteria andIccidNotLike(String value) {
            addCriterion("iccid not like", value, "iccid");
            return this;
        }

        public Criteria andIccidIn(List<String> values) {
            addCriterion("iccid in", values, "iccid");
            return this;
        }

        public Criteria andIccidNotIn(List<String> values) {
            addCriterion("iccid not in", values, "iccid");
            return this;
        }

        public Criteria andIccidBetween(String value1, String value2) {
            addCriterion("iccid between", value1, value2, "iccid");
            return this;
        }

        public Criteria andIccidNotBetween(String value1, String value2) {
            addCriterion("iccid not between", value1, value2, "iccid");
            return this;
        }

        public Criteria andQ1IsNull() {
            addCriterion("q1 is null");
            return this;
        }

        public Criteria andQ1IsNotNull() {
            addCriterion("q1 is not null");
            return this;
        }

        public Criteria andQ1EqualTo(String value) {
            addCriterion("q1 =", value, "q1");
            return this;
        }

        public Criteria andQ1NotEqualTo(String value) {
            addCriterion("q1 <>", value, "q1");
            return this;
        }

        public Criteria andQ1GreaterThan(String value) {
            addCriterion("q1 >", value, "q1");
            return this;
        }

        public Criteria andQ1GreaterThanOrEqualTo(String value) {
            addCriterion("q1 >=", value, "q1");
            return this;
        }

        public Criteria andQ1LessThan(String value) {
            addCriterion("q1 <", value, "q1");
            return this;
        }

        public Criteria andQ1LessThanOrEqualTo(String value) {
            addCriterion("q1 <=", value, "q1");
            return this;
        }

        public Criteria andQ1Like(String value) {
            addCriterion("q1 like", value, "q1");
            return this;
        }

        public Criteria andQ1NotLike(String value) {
            addCriterion("q1 not like", value, "q1");
            return this;
        }

        public Criteria andQ1In(List<String> values) {
            addCriterion("q1 in", values, "q1");
            return this;
        }

        public Criteria andQ1NotIn(List<String> values) {
            addCriterion("q1 not in", values, "q1");
            return this;
        }

        public Criteria andQ1Between(String value1, String value2) {
            addCriterion("q1 between", value1, value2, "q1");
            return this;
        }

        public Criteria andQ1NotBetween(String value1, String value2) {
            addCriterion("q1 not between", value1, value2, "q1");
            return this;
        }

        public Criteria andQ2IsNull() {
            addCriterion("q2 is null");
            return this;
        }

        public Criteria andQ2IsNotNull() {
            addCriterion("q2 is not null");
            return this;
        }

        public Criteria andQ2EqualTo(String value) {
            addCriterion("q2 =", value, "q2");
            return this;
        }

        public Criteria andQ2NotEqualTo(String value) {
            addCriterion("q2 <>", value, "q2");
            return this;
        }

        public Criteria andQ2GreaterThan(String value) {
            addCriterion("q2 >", value, "q2");
            return this;
        }

        public Criteria andQ2GreaterThanOrEqualTo(String value) {
            addCriterion("q2 >=", value, "q2");
            return this;
        }

        public Criteria andQ2LessThan(String value) {
            addCriterion("q2 <", value, "q2");
            return this;
        }

        public Criteria andQ2LessThanOrEqualTo(String value) {
            addCriterion("q2 <=", value, "q2");
            return this;
        }

        public Criteria andQ2Like(String value) {
            addCriterion("q2 like", value, "q2");
            return this;
        }

        public Criteria andQ2NotLike(String value) {
            addCriterion("q2 not like", value, "q2");
            return this;
        }

        public Criteria andQ2In(List<String> values) {
            addCriterion("q2 in", values, "q2");
            return this;
        }

        public Criteria andQ2NotIn(List<String> values) {
            addCriterion("q2 not in", values, "q2");
            return this;
        }

        public Criteria andQ2Between(String value1, String value2) {
            addCriterion("q2 between", value1, value2, "q2");
            return this;
        }

        public Criteria andQ2NotBetween(String value1, String value2) {
            addCriterion("q2 not between", value1, value2, "q2");
            return this;
        }

        public Criteria andQ3IsNull() {
            addCriterion("q3 is null");
            return this;
        }

        public Criteria andQ3IsNotNull() {
            addCriterion("q3 is not null");
            return this;
        }

        public Criteria andQ3EqualTo(String value) {
            addCriterion("q3 =", value, "q3");
            return this;
        }

        public Criteria andQ3NotEqualTo(String value) {
            addCriterion("q3 <>", value, "q3");
            return this;
        }

        public Criteria andQ3GreaterThan(String value) {
            addCriterion("q3 >", value, "q3");
            return this;
        }

        public Criteria andQ3GreaterThanOrEqualTo(String value) {
            addCriterion("q3 >=", value, "q3");
            return this;
        }

        public Criteria andQ3LessThan(String value) {
            addCriterion("q3 <", value, "q3");
            return this;
        }

        public Criteria andQ3LessThanOrEqualTo(String value) {
            addCriterion("q3 <=", value, "q3");
            return this;
        }

        public Criteria andQ3Like(String value) {
            addCriterion("q3 like", value, "q3");
            return this;
        }

        public Criteria andQ3NotLike(String value) {
            addCriterion("q3 not like", value, "q3");
            return this;
        }

        public Criteria andQ3In(List<String> values) {
            addCriterion("q3 in", values, "q3");
            return this;
        }

        public Criteria andQ3NotIn(List<String> values) {
            addCriterion("q3 not in", values, "q3");
            return this;
        }

        public Criteria andQ3Between(String value1, String value2) {
            addCriterion("q3 between", value1, value2, "q3");
            return this;
        }

        public Criteria andQ3NotBetween(String value1, String value2) {
            addCriterion("q3 not between", value1, value2, "q3");
            return this;
        }

        public Criteria andA1IsNull() {
            addCriterion("a1 is null");
            return this;
        }

        public Criteria andA1IsNotNull() {
            addCriterion("a1 is not null");
            return this;
        }

        public Criteria andA1EqualTo(String value) {
            addCriterion("a1 =", value, "a1");
            return this;
        }

        public Criteria andA1NotEqualTo(String value) {
            addCriterion("a1 <>", value, "a1");
            return this;
        }

        public Criteria andA1GreaterThan(String value) {
            addCriterion("a1 >", value, "a1");
            return this;
        }

        public Criteria andA1GreaterThanOrEqualTo(String value) {
            addCriterion("a1 >=", value, "a1");
            return this;
        }

        public Criteria andA1LessThan(String value) {
            addCriterion("a1 <", value, "a1");
            return this;
        }

        public Criteria andA1LessThanOrEqualTo(String value) {
            addCriterion("a1 <=", value, "a1");
            return this;
        }

        public Criteria andA1Like(String value) {
            addCriterion("a1 like", value, "a1");
            return this;
        }

        public Criteria andA1NotLike(String value) {
            addCriterion("a1 not like", value, "a1");
            return this;
        }

        public Criteria andA1In(List<String> values) {
            addCriterion("a1 in", values, "a1");
            return this;
        }

        public Criteria andA1NotIn(List<String> values) {
            addCriterion("a1 not in", values, "a1");
            return this;
        }

        public Criteria andA1Between(String value1, String value2) {
            addCriterion("a1 between", value1, value2, "a1");
            return this;
        }

        public Criteria andA1NotBetween(String value1, String value2) {
            addCriterion("a1 not between", value1, value2, "a1");
            return this;
        }

        public Criteria andA2IsNull() {
            addCriterion("a2 is null");
            return this;
        }

        public Criteria andA2IsNotNull() {
            addCriterion("a2 is not null");
            return this;
        }

        public Criteria andA2EqualTo(String value) {
            addCriterion("a2 =", value, "a2");
            return this;
        }

        public Criteria andA2NotEqualTo(String value) {
            addCriterion("a2 <>", value, "a2");
            return this;
        }

        public Criteria andA2GreaterThan(String value) {
            addCriterion("a2 >", value, "a2");
            return this;
        }

        public Criteria andA2GreaterThanOrEqualTo(String value) {
            addCriterion("a2 >=", value, "a2");
            return this;
        }

        public Criteria andA2LessThan(String value) {
            addCriterion("a2 <", value, "a2");
            return this;
        }

        public Criteria andA2LessThanOrEqualTo(String value) {
            addCriterion("a2 <=", value, "a2");
            return this;
        }

        public Criteria andA2Like(String value) {
            addCriterion("a2 like", value, "a2");
            return this;
        }

        public Criteria andA2NotLike(String value) {
            addCriterion("a2 not like", value, "a2");
            return this;
        }

        public Criteria andA2In(List<String> values) {
            addCriterion("a2 in", values, "a2");
            return this;
        }

        public Criteria andA2NotIn(List<String> values) {
            addCriterion("a2 not in", values, "a2");
            return this;
        }

        public Criteria andA2Between(String value1, String value2) {
            addCriterion("a2 between", value1, value2, "a2");
            return this;
        }

        public Criteria andA2NotBetween(String value1, String value2) {
            addCriterion("a2 not between", value1, value2, "a2");
            return this;
        }

        public Criteria andA3IsNull() {
            addCriterion("a3 is null");
            return this;
        }

        public Criteria andA3IsNotNull() {
            addCriterion("a3 is not null");
            return this;
        }

        public Criteria andA3EqualTo(String value) {
            addCriterion("a3 =", value, "a3");
            return this;
        }

        public Criteria andA3NotEqualTo(String value) {
            addCriterion("a3 <>", value, "a3");
            return this;
        }

        public Criteria andA3GreaterThan(String value) {
            addCriterion("a3 >", value, "a3");
            return this;
        }

        public Criteria andA3GreaterThanOrEqualTo(String value) {
            addCriterion("a3 >=", value, "a3");
            return this;
        }

        public Criteria andA3LessThan(String value) {
            addCriterion("a3 <", value, "a3");
            return this;
        }

        public Criteria andA3LessThanOrEqualTo(String value) {
            addCriterion("a3 <=", value, "a3");
            return this;
        }

        public Criteria andA3Like(String value) {
            addCriterion("a3 like", value, "a3");
            return this;
        }

        public Criteria andA3NotLike(String value) {
            addCriterion("a3 not like", value, "a3");
            return this;
        }

        public Criteria andA3In(List<String> values) {
            addCriterion("a3 in", values, "a3");
            return this;
        }

        public Criteria andA3NotIn(List<String> values) {
            addCriterion("a3 not in", values, "a3");
            return this;
        }

        public Criteria andA3Between(String value1, String value2) {
            addCriterion("a3 between", value1, value2, "a3");
            return this;
        }

        public Criteria andA3NotBetween(String value1, String value2) {
            addCriterion("a3 not between", value1, value2, "a3");
            return this;
        }
    }
}
