package com.nali.spreader.model;

import java.io.Serializable;
import java.util.Date;

public class Client implements Serializable {

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.id
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.user_name
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private String userName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.pwd
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private String pwd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.real_name
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private String realName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.id_card
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private String idCard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.sex
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private Integer sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.cellphone
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private String cellphone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.tel
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private String tel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.address
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private String address;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.post_code
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private Integer postCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.qq
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private Integer qq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.msn
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private String msn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.latest_login_time
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private Date latestLoginTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.latest_login_ip
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private String latestLoginIp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.register_time
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private Date registerTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client.version
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    private String version;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.id
     *
     * @return the value of spreader.tb_client.id
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.id
     *
     * @param id the value for spreader.tb_client.id
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.user_name
     *
     * @return the value of spreader.tb_client.user_name
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.user_name
     *
     * @param userName the value for spreader.tb_client.user_name
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.pwd
     *
     * @return the value of spreader.tb_client.pwd
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.pwd
     *
     * @param pwd the value for spreader.tb_client.pwd
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.real_name
     *
     * @return the value of spreader.tb_client.real_name
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.real_name
     *
     * @param realName the value for spreader.tb_client.real_name
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.id_card
     *
     * @return the value of spreader.tb_client.id_card
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.id_card
     *
     * @param idCard the value for spreader.tb_client.id_card
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.sex
     *
     * @return the value of spreader.tb_client.sex
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.sex
     *
     * @param sex the value for spreader.tb_client.sex
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.cellphone
     *
     * @return the value of spreader.tb_client.cellphone
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.cellphone
     *
     * @param cellphone the value for spreader.tb_client.cellphone
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.tel
     *
     * @return the value of spreader.tb_client.tel
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.tel
     *
     * @param tel the value for spreader.tb_client.tel
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.address
     *
     * @return the value of spreader.tb_client.address
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.address
     *
     * @param address the value for spreader.tb_client.address
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.post_code
     *
     * @return the value of spreader.tb_client.post_code
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public Integer getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.post_code
     *
     * @param postCode the value for spreader.tb_client.post_code
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setPostCode(Integer postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.qq
     *
     * @return the value of spreader.tb_client.qq
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public Integer getQq() {
        return qq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.qq
     *
     * @param qq the value for spreader.tb_client.qq
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setQq(Integer qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.msn
     *
     * @return the value of spreader.tb_client.msn
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.msn
     *
     * @param msn the value for spreader.tb_client.msn
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setMsn(String msn) {
        this.msn = msn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.latest_login_time
     *
     * @return the value of spreader.tb_client.latest_login_time
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public Date getLatestLoginTime() {
        return latestLoginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.latest_login_time
     *
     * @param latestLoginTime the value for spreader.tb_client.latest_login_time
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setLatestLoginTime(Date latestLoginTime) {
        this.latestLoginTime = latestLoginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.latest_login_ip
     *
     * @return the value of spreader.tb_client.latest_login_ip
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public String getLatestLoginIp() {
        return latestLoginIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.latest_login_ip
     *
     * @param latestLoginIp the value for spreader.tb_client.latest_login_ip
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setLatestLoginIp(String latestLoginIp) {
        this.latestLoginIp = latestLoginIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.register_time
     *
     * @return the value of spreader.tb_client.register_time
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.register_time
     *
     * @param registerTime the value for spreader.tb_client.register_time
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client.version
     *
     * @return the value of spreader.tb_client.version
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client.version
     *
     * @param version the value for spreader.tb_client.version
     *
     * @ibatorgenerated Sat Mar 12 17:19:21 CST 2011
     */
    public void setVersion(String version) {
        this.version = version;
    }
}
