package com.nali.spreader.model;

import java.io.Serializable;
import java.util.Date;
import com.nali.common.model.BaseModel;

public class RobotUser extends BaseModel implements Serializable {

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_robot_user.uid
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private Long uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_robot_user.website_id
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private Integer websiteId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_robot_user.profile_id
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private Long profileId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_robot_user.admin_id
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private Integer adminId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_robot_user.level
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private Integer level;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_robot_user.register_time
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private Date registerTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_robot_user.home_url
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private String homeUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_robot_user.score
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private Integer score;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_robot_user.fans_count
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private Integer fansCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_robot_user.followed_count
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    private Integer followedCount;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_robot_user.uid
     *
     * @return the value of spreader.tb_robot_user.uid
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_robot_user.uid
     *
     * @param uid the value for spreader.tb_robot_user.uid
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_robot_user.website_id
     *
     * @return the value of spreader.tb_robot_user.website_id
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_robot_user.website_id
     *
     * @param websiteId the value for spreader.tb_robot_user.website_id
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_robot_user.profile_id
     *
     * @return the value of spreader.tb_robot_user.profile_id
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Long getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_robot_user.profile_id
     *
     * @param profileId the value for spreader.tb_robot_user.profile_id
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void setProfileId(Long profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_robot_user.admin_id
     *
     * @return the value of spreader.tb_robot_user.admin_id
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_robot_user.admin_id
     *
     * @param adminId the value for spreader.tb_robot_user.admin_id
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_robot_user.level
     *
     * @return the value of spreader.tb_robot_user.level
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_robot_user.level
     *
     * @param level the value for spreader.tb_robot_user.level
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_robot_user.register_time
     *
     * @return the value of spreader.tb_robot_user.register_time
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_robot_user.register_time
     *
     * @param registerTime the value for spreader.tb_robot_user.register_time
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_robot_user.home_url
     *
     * @return the value of spreader.tb_robot_user.home_url
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public String getHomeUrl() {
        return homeUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_robot_user.home_url
     *
     * @param homeUrl the value for spreader.tb_robot_user.home_url
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void setHomeUrl(String homeUrl) {
        this.homeUrl = homeUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_robot_user.score
     *
     * @return the value of spreader.tb_robot_user.score
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_robot_user.score
     *
     * @param score the value for spreader.tb_robot_user.score
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_robot_user.fans_count
     *
     * @return the value of spreader.tb_robot_user.fans_count
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Integer getFansCount() {
        return fansCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_robot_user.fans_count
     *
     * @param fansCount the value for spreader.tb_robot_user.fans_count
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void setFansCount(Integer fansCount) {
        this.fansCount = fansCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_robot_user.followed_count
     *
     * @return the value of spreader.tb_robot_user.followed_count
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public Integer getFollowedCount() {
        return followedCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_robot_user.followed_count
     *
     * @param followedCount the value for spreader.tb_robot_user.followed_count
     *
     * @ibatorgenerated Fri Mar 25 20:53:45 CST 2011
     */
    public void setFollowedCount(Integer followedCount) {
        this.followedCount = followedCount;
    }
}
