package com.nali.spreader.model;

import com.nali.common.model.Limit;
import com.nali.common.model.Shard;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TaskTypeExample {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Thu Mar 31 15:39:16 CST 2011
     */
    public TaskTypeExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Thu Mar 31 15:39:16 CST 2011
     */
    protected TaskTypeExample(TaskTypeExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.limit = example.limit;
        this.shard = example.shard;
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    private Shard shard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    private Limit limit;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public void setShard(Shard shard) {
        this.shard = shard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public void setLimit(Limit limit) {
        this.limit = limit;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public static class Criteria {

        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andTaskTypeIsNull() {
            addCriterion("task_type is null");
            return this;
        }

        public Criteria andTaskTypeIsNotNull() {
            addCriterion("task_type is not null");
            return this;
        }

        public Criteria andTaskTypeEqualTo(Integer value) {
            addCriterion("task_type =", value, "taskType");
            return this;
        }

        public Criteria andTaskTypeNotEqualTo(Integer value) {
            addCriterion("task_type <>", value, "taskType");
            return this;
        }

        public Criteria andTaskTypeGreaterThan(Integer value) {
            addCriterion("task_type >", value, "taskType");
            return this;
        }

        public Criteria andTaskTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_type >=", value, "taskType");
            return this;
        }

        public Criteria andTaskTypeLessThan(Integer value) {
            addCriterion("task_type <", value, "taskType");
            return this;
        }

        public Criteria andTaskTypeLessThanOrEqualTo(Integer value) {
            addCriterion("task_type <=", value, "taskType");
            return this;
        }

        public Criteria andTaskTypeIn(List values) {
            addCriterion("task_type in", values, "taskType");
            return this;
        }

        public Criteria andTaskTypeNotIn(List values) {
            addCriterion("task_type not in", values, "taskType");
            return this;
        }

        public Criteria andTaskTypeBetween(Integer value1, Integer value2) {
            addCriterion("task_type between", value1, value2, "taskType");
            return this;
        }

        public Criteria andTaskTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("task_type not between", value1, value2, "taskType");
            return this;
        }

        public Criteria andBatchSizeIsNull() {
            addCriterion("batch_size is null");
            return this;
        }

        public Criteria andBatchSizeIsNotNull() {
            addCriterion("batch_size is not null");
            return this;
        }

        public Criteria andBatchSizeEqualTo(Integer value) {
            addCriterion("batch_size =", value, "batchSize");
            return this;
        }

        public Criteria andBatchSizeNotEqualTo(Integer value) {
            addCriterion("batch_size <>", value, "batchSize");
            return this;
        }

        public Criteria andBatchSizeGreaterThan(Integer value) {
            addCriterion("batch_size >", value, "batchSize");
            return this;
        }

        public Criteria andBatchSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("batch_size >=", value, "batchSize");
            return this;
        }

        public Criteria andBatchSizeLessThan(Integer value) {
            addCriterion("batch_size <", value, "batchSize");
            return this;
        }

        public Criteria andBatchSizeLessThanOrEqualTo(Integer value) {
            addCriterion("batch_size <=", value, "batchSize");
            return this;
        }

        public Criteria andBatchSizeIn(List values) {
            addCriterion("batch_size in", values, "batchSize");
            return this;
        }

        public Criteria andBatchSizeNotIn(List values) {
            addCriterion("batch_size not in", values, "batchSize");
            return this;
        }

        public Criteria andBatchSizeBetween(Integer value1, Integer value2) {
            addCriterion("batch_size between", value1, value2, "batchSize");
            return this;
        }

        public Criteria andBatchSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("batch_size not between", value1, value2, "batchSize");
            return this;
        }

        public Criteria andHasWebContentIsNull() {
            addCriterion("has_web_content is null");
            return this;
        }

        public Criteria andHasWebContentIsNotNull() {
            addCriterion("has_web_content is not null");
            return this;
        }

        public Criteria andHasWebContentEqualTo(Boolean value) {
            addCriterion("has_web_content =", value, "hasWebContent");
            return this;
        }

        public Criteria andHasWebContentNotEqualTo(Boolean value) {
            addCriterion("has_web_content <>", value, "hasWebContent");
            return this;
        }

        public Criteria andHasWebContentGreaterThan(Boolean value) {
            addCriterion("has_web_content >", value, "hasWebContent");
            return this;
        }

        public Criteria andHasWebContentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("has_web_content >=", value, "hasWebContent");
            return this;
        }

        public Criteria andHasWebContentLessThan(Boolean value) {
            addCriterion("has_web_content <", value, "hasWebContent");
            return this;
        }

        public Criteria andHasWebContentLessThanOrEqualTo(Boolean value) {
            addCriterion("has_web_content <=", value, "hasWebContent");
            return this;
        }

        public Criteria andHasWebContentIn(List values) {
            addCriterion("has_web_content in", values, "hasWebContent");
            return this;
        }

        public Criteria andHasWebContentNotIn(List values) {
            addCriterion("has_web_content not in", values, "hasWebContent");
            return this;
        }

        public Criteria andHasWebContentBetween(Boolean value1, Boolean value2) {
            addCriterion("has_web_content between", value1, value2, "hasWebContent");
            return this;
        }

        public Criteria andHasWebContentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("has_web_content not between", value1, value2, "hasWebContent");
            return this;
        }
    }
}
