package com.nali.spreader.model;

import java.io.Serializable;
import com.nali.spreader.repo.Resource;

public class TaskType implements Serializable, Resource {

    @Override
    public Integer getId() {
        return taskType;
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task_type.task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    private Integer taskType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task_type.batch_size
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    private Integer batchSize;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task_type.has_web_content
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    private Boolean hasWebContent;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task_type.task_type
     *
     * @return the value of spreader.tb_task_type.task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task_type.task_type
     *
     * @param taskType the value for spreader.tb_task_type.task_type
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task_type.batch_size
     *
     * @return the value of spreader.tb_task_type.batch_size
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public Integer getBatchSize() {
        return batchSize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task_type.batch_size
     *
     * @param batchSize the value for spreader.tb_task_type.batch_size
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public void setBatchSize(Integer batchSize) {
        this.batchSize = batchSize;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task_type.has_web_content
     *
     * @return the value of spreader.tb_task_type.has_web_content
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public Boolean getHasWebContent() {
        return hasWebContent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task_type.has_web_content
     *
     * @param hasWebContent the value for spreader.tb_task_type.has_web_content
     *
     * @ibatorgenerated Sat Apr 02 16:57:14 CST 2011
     */
    public void setHasWebContent(Boolean hasWebContent) {
        this.hasWebContent = hasWebContent;
    }
}
