package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudUserRelationDao;
import com.nali.spreader.model.TbUserRelationKey;
import com.nali.spreader.model.UserRelationExample;

@Repository
public class CrudUserRelationDao implements ICrudUserRelationDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:16:22 CST 2011
     */
    public CrudUserRelationDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int countByExample(UserRelationExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_user_relation.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int deleteByExample(UserRelationExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_user_relation.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int deleteByPrimaryKey(TbUserRelationKey key) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_user_relation.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public void insert(TbUserRelationKey record) {
        getSqlMapClientTemplate().insert("spreader_tb_user_relation.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public void insertSelective(TbUserRelationKey record) {
        getSqlMapClientTemplate().insert("spreader_tb_user_relation.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<TbUserRelationKey> selectByExample(UserRelationExample example) {
        List<TbUserRelationKey> list = getSqlMapClientTemplate().queryForList("spreader_tb_user_relation.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int updateByExampleSelective(TbUserRelationKey record, UserRelationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_user_relation.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int updateByExample(TbUserRelationKey record, UserRelationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_user_relation.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_user_relation
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    private static class UpdateByExampleParms extends UserRelationExample {

        private Object record;

        public UpdateByExampleParms(Object record, UserRelationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
