package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudClientConfigDao;
import com.nali.spreader.model.ClientConfig;
import com.nali.spreader.model.ClientConfigExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudClientConfigDao implements ICrudClientConfigDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    public CrudClientConfigDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public int countByExample(ClientConfigExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_client_config.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public int deleteByExample(ClientConfigExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_client_config.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        ClientConfig key = new ClientConfig();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_client_config.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public Long insert(ClientConfig record) {
        Object newKey = getSqlMapClientTemplate().insert("spreader_tb_client_config.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public Long insertSelective(ClientConfig record) {
        Object newKey = getSqlMapClientTemplate().insert("spreader_tb_client_config.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<ClientConfig> selectByExampleWithBLOBs(ClientConfigExample example) {
        List<ClientConfig> list = getSqlMapClientTemplate().queryForList("spreader_tb_client_config.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<ClientConfig> selectByExampleWithoutBLOBs(ClientConfigExample example) {
        List<ClientConfig> list = getSqlMapClientTemplate().queryForList("spreader_tb_client_config.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public ClientConfig selectByPrimaryKey(Long id) {
        ClientConfig key = new ClientConfig();
        key.setId(id);
        ClientConfig record = (ClientConfig) getSqlMapClientTemplate().queryForObject("spreader_tb_client_config.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public int updateByExampleSelective(ClientConfig record, ClientConfigExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_client_config.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public int updateByExampleWithBLOBs(ClientConfig record, ClientConfigExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_client_config.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public int updateByExampleWithoutBLOBs(ClientConfig record, ClientConfigExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_client_config.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public int updateByPrimaryKeySelective(ClientConfig record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_client_config.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public int updateByPrimaryKeyWithBLOBs(ClientConfig record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_client_config.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public int updateByPrimaryKeyWithoutBLOBs(ClientConfig record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_client_config.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Mon Aug 26 16:54:23 CST 2013
     */
    private static class UpdateByExampleParms extends ClientConfigExample {

        private Object record;

        public UpdateByExampleParms(Object record, ClientConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
