package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudLoginFailInfoDao;
import com.nali.spreader.model.LoginFailInfo;
import com.nali.spreader.model.LoginFailInfoExample;

@Repository
public class CrudLoginFailInfoDao implements ICrudLoginFailInfoDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public CrudLoginFailInfoDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int countByExample(LoginFailInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_login_fail_info.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int deleteByExample(LoginFailInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_login_fail_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int deleteByPrimaryKey(Long id) {
        LoginFailInfo key = new LoginFailInfo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_login_fail_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public void insert(LoginFailInfo record) {
        getSqlMapClientTemplate().insert("spreader_tb_login_fail_info.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public void insertSelective(LoginFailInfo record) {
        getSqlMapClientTemplate().insert("spreader_tb_login_fail_info.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<LoginFailInfo> selectByExampleWithBLOBs(LoginFailInfoExample example) {
        List<LoginFailInfo> list = getSqlMapClientTemplate().queryForList("spreader_tb_login_fail_info.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<LoginFailInfo> selectByExampleWithoutBLOBs(LoginFailInfoExample example) {
        List<LoginFailInfo> list = getSqlMapClientTemplate().queryForList("spreader_tb_login_fail_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public LoginFailInfo selectByPrimaryKey(Long id) {
        LoginFailInfo key = new LoginFailInfo();
        key.setId(id);
        LoginFailInfo record = (LoginFailInfo) getSqlMapClientTemplate().queryForObject("spreader_tb_login_fail_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int updateByExampleSelective(LoginFailInfo record, LoginFailInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_login_fail_info.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int updateByExampleWithBLOBs(LoginFailInfo record, LoginFailInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_login_fail_info.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int updateByExampleWithoutBLOBs(LoginFailInfo record, LoginFailInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_login_fail_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int updateByPrimaryKeySelective(LoginFailInfo record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_login_fail_info.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int updateByPrimaryKeyWithBLOBs(LoginFailInfo record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_login_fail_info.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public int updateByPrimaryKeyWithoutBLOBs(LoginFailInfo record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_login_fail_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_login_fail_info
     *
     * @ibatorgenerated Mon Jul 18 15:02:49 CST 2011
     */
    private static class UpdateByExampleParms extends LoginFailInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, LoginFailInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}