package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudActionStepDao;
import com.nali.spreader.model.ActionStep;
import com.nali.spreader.model.ActionStepExample;
import com.nali.spreader.model.TbActionStepWithBLOBs;

@Repository
public class CrudActionStepDao implements ICrudActionStepDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:16:21 CST 2011
     */
    public CrudActionStepDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public int countByExample(ActionStepExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_action_step.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public int deleteByExample(ActionStepExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_action_step.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public int deleteByPrimaryKey(Long id) {
        ActionStep key = new ActionStep();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_action_step.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public void insert(TbActionStepWithBLOBs record) {
        getSqlMapClientTemplate().insert("spreader_tb_action_step.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public void insertSelective(TbActionStepWithBLOBs record) {
        getSqlMapClientTemplate().insert("spreader_tb_action_step.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<TbActionStepWithBLOBs> selectByExampleWithBLOBs(ActionStepExample example) {
        List<TbActionStepWithBLOBs> list = getSqlMapClientTemplate().queryForList("spreader_tb_action_step.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<ActionStep> selectByExampleWithoutBLOBs(ActionStepExample example) {
        List<ActionStep> list = getSqlMapClientTemplate().queryForList("spreader_tb_action_step.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public TbActionStepWithBLOBs selectByPrimaryKey(Long id) {
        ActionStep key = new ActionStep();
        key.setId(id);
        TbActionStepWithBLOBs record = (TbActionStepWithBLOBs) getSqlMapClientTemplate().queryForObject("spreader_tb_action_step.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public int updateByExampleSelective(TbActionStepWithBLOBs record, ActionStepExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_action_step.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public int updateByExample(TbActionStepWithBLOBs record, ActionStepExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_action_step.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public int updateByExample(ActionStep record, ActionStepExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_action_step.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public int updateByPrimaryKeySelective(TbActionStepWithBLOBs record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_action_step.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public int updateByPrimaryKey(TbActionStepWithBLOBs record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_action_step.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public int updateByPrimaryKey(ActionStep record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_action_step.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    private static class UpdateByExampleParms extends ActionStepExample {

        private Object record;

        public UpdateByExampleParms(Object record, ActionStepExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
