package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudUserContentDao;
import com.nali.spreader.model.TbUserContentKey;
import com.nali.spreader.model.UserContentExample;

@Repository
public class CrudUserContentDao implements ICrudUserContentDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:16:22 CST 2011
     */
    public CrudUserContentDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int countByExample(UserContentExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_user_content.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int deleteByExample(UserContentExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_user_content.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int deleteByPrimaryKey(TbUserContentKey key) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_user_content.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public void insert(TbUserContentKey record) {
        getSqlMapClientTemplate().insert("spreader_tb_user_content.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public void insertSelective(TbUserContentKey record) {
        getSqlMapClientTemplate().insert("spreader_tb_user_content.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<TbUserContentKey> selectByExample(UserContentExample example) {
        List<TbUserContentKey> list = getSqlMapClientTemplate().queryForList("spreader_tb_user_content.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int updateByExampleSelective(TbUserContentKey record, UserContentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_user_content.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public int updateByExample(TbUserContentKey record, UserContentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_user_content.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_user_content
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    private static class UpdateByExampleParms extends UserContentExample {

        private Object record;

        public UpdateByExampleParms(Object record, UserContentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
