package com.nali.spreader.data;

import com.nali.common.model.BaseModel;
import java.io.Serializable;

public class ContentKeyword extends BaseModel implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_content_keyword.id
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_content_keyword.content_id
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    private Long contentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_content_keyword.keyword_id
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    private Long keywordId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_content_keyword.id
     *
     * @return the value of spreader.tb_content_keyword.id
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_content_keyword.id
     *
     * @param id the value for spreader.tb_content_keyword.id
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_content_keyword.content_id
     *
     * @return the value of spreader.tb_content_keyword.content_id
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_content_keyword.content_id
     *
     * @param contentId the value for spreader.tb_content_keyword.content_id
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_content_keyword.keyword_id
     *
     * @return the value of spreader.tb_content_keyword.keyword_id
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public Long getKeywordId() {
        return keywordId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_content_keyword.keyword_id
     *
     * @param keywordId the value for spreader.tb_content_keyword.keyword_id
     *
     * @ibatorgenerated Tue Jun 05 17:11:09 CST 2012
     */
    public void setKeywordId(Long keywordId) {
        this.keywordId = keywordId;
    }
}