package com.nali.spreader.data;

import java.io.Serializable;
import java.util.Date;

import com.nali.common.model.BaseModel;

public class Photo extends BaseModel implements Serializable {

    private static final long serialVersionUID = -7546397080652814122L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_photo.id
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_photo.gender
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    private Integer gender;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_photo.uid
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    private Long uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_photo.pic_type
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    private String picType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_photo.pic_url
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    private String picUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_photo.createtime
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    private Date createtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_photo.avatarflg
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    private Boolean avatarflg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_photo.photolibflg
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    private Boolean photolibflg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_photo.pic
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    private byte[] pic;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_photo.id
     *
     * @return the value of spreader.tb_photo.id
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_photo.id
     *
     * @param id the value for spreader.tb_photo.id
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_photo.gender
     *
     * @return the value of spreader.tb_photo.gender
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_photo.gender
     *
     * @param gender the value for spreader.tb_photo.gender
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_photo.uid
     *
     * @return the value of spreader.tb_photo.uid
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_photo.uid
     *
     * @param uid the value for spreader.tb_photo.uid
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_photo.pic_type
     *
     * @return the value of spreader.tb_photo.pic_type
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public String getPicType() {
        return picType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_photo.pic_type
     *
     * @param picType the value for spreader.tb_photo.pic_type
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public void setPicType(String picType) {
        this.picType = picType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_photo.pic_url
     *
     * @return the value of spreader.tb_photo.pic_url
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_photo.pic_url
     *
     * @param picUrl the value for spreader.tb_photo.pic_url
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_photo.createtime
     *
     * @return the value of spreader.tb_photo.createtime
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_photo.createtime
     *
     * @param createtime the value for spreader.tb_photo.createtime
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_photo.avatarflg
     *
     * @return the value of spreader.tb_photo.avatarflg
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public Boolean getAvatarflg() {
        return avatarflg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_photo.avatarflg
     *
     * @param avatarflg the value for spreader.tb_photo.avatarflg
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public void setAvatarflg(Boolean avatarflg) {
        this.avatarflg = avatarflg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_photo.photolibflg
     *
     * @return the value of spreader.tb_photo.photolibflg
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public Boolean getPhotolibflg() {
        return photolibflg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_photo.photolibflg
     *
     * @param photolibflg the value for spreader.tb_photo.photolibflg
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public void setPhotolibflg(Boolean photolibflg) {
        this.photolibflg = photolibflg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_photo.pic
     *
     * @return the value of spreader.tb_photo.pic
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public byte[] getPic() {
        return pic;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_photo.pic
     *
     * @param pic the value for spreader.tb_photo.pic
     *
     * @ibatorgenerated Thu Dec 15 11:45:43 CST 2011
     */
    public void setPic(byte[] pic) {
        this.pic = pic;
    }
}
