package com.nali.spreader.data;

import com.nali.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class Content extends BaseModel implements Serializable {
    private static final long serialVersionUID = -5017302600914628315L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_content.id
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_content.type
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_content.title
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    private String title;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_content.uid
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    private Long uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_content.pub_date
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    private Date pubDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_content.sync_date
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    private Date syncDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_content.content
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    private String content;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_content.id
     *
     * @return the value of spreader.tb_content.id
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_content.id
     *
     * @param id the value for spreader.tb_content.id
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_content.type
     *
     * @return the value of spreader.tb_content.type
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_content.type
     *
     * @param type the value for spreader.tb_content.type
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_content.title
     *
     * @return the value of spreader.tb_content.title
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_content.title
     *
     * @param title the value for spreader.tb_content.title
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_content.uid
     *
     * @return the value of spreader.tb_content.uid
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_content.uid
     *
     * @param uid the value for spreader.tb_content.uid
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_content.pub_date
     *
     * @return the value of spreader.tb_content.pub_date
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public Date getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_content.pub_date
     *
     * @param pubDate the value for spreader.tb_content.pub_date
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_content.sync_date
     *
     * @return the value of spreader.tb_content.sync_date
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public Date getSyncDate() {
        return syncDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_content.sync_date
     *
     * @param syncDate the value for spreader.tb_content.sync_date
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public void setSyncDate(Date syncDate) {
        this.syncDate = syncDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_content.content
     *
     * @return the value of spreader.tb_content.content
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_content.content
     *
     * @param content the value for spreader.tb_content.content
     *
     * @ibatorgenerated Fri Aug 12 15:49:59 CST 2011
     */
    public void setContent(String content) {
        this.content = content;
    }
}