package com.nali.spreader.dao;

import com.nali.spreader.model.Task;
import com.nali.spreader.model.TaskExample;
import java.util.List;

public interface ICrudTaskDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    int countByExample(TaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    void insert(Task record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    void insertSelective(Task record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    List selectByExampleWithBLOBs(TaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    List selectByExampleWithoutBLOBs(TaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    Task selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    int updateByExampleSelective(Task record, TaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    int updateByExampleWithBLOBs(Task record, TaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    int updateByExampleWithoutBLOBs(Task record, TaskExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    int updateByPrimaryKeyWithBLOBs(Task record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_task
     *
     * @ibatorgenerated Fri Mar 25 20:53:46 CST 2011
     */
    int updateByPrimaryKeyWithoutBLOBs(Task record);
}
