package com.nali.spreader.model;

import com.nali.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class Task extends BaseModel implements Serializable {

    private static final long serialVersionUID = 993460196457000644L;

    public static final Integer STATUS_INIT = 0;

    public static final Integer STATUS_SUCCESS = 1;

    public static final Integer STATUS_FAILED = 2;

    public static final Integer STATUS_GIVED_UP = 3;

    public static final Integer STATUS_EXPIRED = 4;

    public static final Integer STATUS_EXCEPTION = 5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task.id
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task.task_code
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private String taskCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task.bid
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private Long bid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task.start_time
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private Date startTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task.handle_time
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private Date handleTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task.status
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task.uid
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private Long uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task.create_time
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task.result_id
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private Long resultId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_task.trace_link
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    private String traceLink;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task.id
     *
     * @return the value of spreader.tb_task.id
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task.id
     *
     * @param id the value for spreader.tb_task.id
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task.task_code
     *
     * @return the value of spreader.tb_task.task_code
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task.task_code
     *
     * @param taskCode the value for spreader.tb_task.task_code
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task.bid
     *
     * @return the value of spreader.tb_task.bid
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public Long getBid() {
        return bid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task.bid
     *
     * @param bid the value for spreader.tb_task.bid
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void setBid(Long bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task.start_time
     *
     * @return the value of spreader.tb_task.start_time
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task.start_time
     *
     * @param startTime the value for spreader.tb_task.start_time
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task.handle_time
     *
     * @return the value of spreader.tb_task.handle_time
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task.handle_time
     *
     * @param handleTime the value for spreader.tb_task.handle_time
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task.status
     *
     * @return the value of spreader.tb_task.status
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task.status
     *
     * @param status the value for spreader.tb_task.status
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task.uid
     *
     * @return the value of spreader.tb_task.uid
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task.uid
     *
     * @param uid the value for spreader.tb_task.uid
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task.create_time
     *
     * @return the value of spreader.tb_task.create_time
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task.create_time
     *
     * @param createTime the value for spreader.tb_task.create_time
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task.result_id
     *
     * @return the value of spreader.tb_task.result_id
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public Long getResultId() {
        return resultId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task.result_id
     *
     * @param resultId the value for spreader.tb_task.result_id
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void setResultId(Long resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_task.trace_link
     *
     * @return the value of spreader.tb_task.trace_link
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public String getTraceLink() {
        return traceLink;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_task.trace_link
     *
     * @param traceLink the value for spreader.tb_task.trace_link
     *
     * @ibatorgenerated Wed Mar 21 15:07:47 CST 2012
     */
    public void setTraceLink(String traceLink) {
        this.traceLink = traceLink;
    }
}
