package com.nali.spreader.data;

import com.nali.common.model.BaseModel;
import java.io.Serializable;

public class AppPurchase extends BaseModel implements Serializable {
    private static final long serialVersionUID = 6982635010048045385L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_app_purchase.appid
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    private Long appid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_app_purchase.info_type
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    private Integer infoType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_app_purchase.assign_count
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    private Integer assignCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_app_purchase.confirm_count
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    private Integer confirmCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_app_purchase.info
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    private byte[] info;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_app_purchase.appid
     *
     * @return the value of spreader.tb_app_purchase.appid
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public Long getAppid() {
        return appid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_app_purchase.appid
     *
     * @param appid the value for spreader.tb_app_purchase.appid
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public void setAppid(Long appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_app_purchase.info_type
     *
     * @return the value of spreader.tb_app_purchase.info_type
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public Integer getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_app_purchase.info_type
     *
     * @param infoType the value for spreader.tb_app_purchase.info_type
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public void setInfoType(Integer infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_app_purchase.assign_count
     *
     * @return the value of spreader.tb_app_purchase.assign_count
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public Integer getAssignCount() {
        return assignCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_app_purchase.assign_count
     *
     * @param assignCount the value for spreader.tb_app_purchase.assign_count
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public void setAssignCount(Integer assignCount) {
        this.assignCount = assignCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_app_purchase.confirm_count
     *
     * @return the value of spreader.tb_app_purchase.confirm_count
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public Integer getConfirmCount() {
        return confirmCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_app_purchase.confirm_count
     *
     * @param confirmCount the value for spreader.tb_app_purchase.confirm_count
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public void setConfirmCount(Integer confirmCount) {
        this.confirmCount = confirmCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_app_purchase.info
     *
     * @return the value of spreader.tb_app_purchase.info
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public byte[] getInfo() {
        return info;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_app_purchase.info
     *
     * @param info the value for spreader.tb_app_purchase.info
     *
     * @ibatorgenerated Mon Apr 08 17:25:00 CST 2013
     */
    public void setInfo(byte[] info) {
        this.info = info;
    }
}