package com.nali.spreader.data;

import com.nali.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class ContentReplay extends BaseModel implements Serializable {

	private static final long serialVersionUID = -3998651701885277678L;

	/**
	 * 引用的评论
	 */
	private ContentReplay refReplay;

	/**
	 * 引用的微博
	 */
	private Content refContent;

	/**
	 * 消息来源作者
	 */
	private Long fromWebsiteUid;

	public Long getFromWebsiteUid() {
		return fromWebsiteUid;
	}

	public void setFromWebsiteUid(Long fromWebsiteUid) {
		this.fromWebsiteUid = fromWebsiteUid;
	}

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column spreader.tb_content_replay.id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	private Long id;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column spreader.tb_content_replay.from_uid
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	private Long fromUid;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column spreader.tb_content_replay.to_uid
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	private Long toUid;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column spreader.tb_content_replay.content_id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	private Long contentId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column spreader.tb_content_replay.content
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	private String content;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column spreader.tb_content_replay.pub_date
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	private Date pubDate;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column spreader.tb_content_replay.website_id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	private Integer websiteId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column spreader.tb_content_replay.ref_id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	private Long refId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column spreader.tb_content_replay.id
	 * 
	 * @return the value of spreader.tb_content_replay.id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column spreader.tb_content_replay.id
	 * 
	 * @param id
	 *            the value for spreader.tb_content_replay.id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column spreader.tb_content_replay.from_uid
	 * 
	 * @return the value of spreader.tb_content_replay.from_uid
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public Long getFromUid() {
		return fromUid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column spreader.tb_content_replay.from_uid
	 * 
	 * @param fromUid
	 *            the value for spreader.tb_content_replay.from_uid
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public void setFromUid(Long fromUid) {
		this.fromUid = fromUid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column spreader.tb_content_replay.to_uid
	 * 
	 * @return the value of spreader.tb_content_replay.to_uid
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public Long getToUid() {
		return toUid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column spreader.tb_content_replay.to_uid
	 * 
	 * @param toUid
	 *            the value for spreader.tb_content_replay.to_uid
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public void setToUid(Long toUid) {
		this.toUid = toUid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column spreader.tb_content_replay.content_id
	 * 
	 * @return the value of spreader.tb_content_replay.content_id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public Long getContentId() {
		return contentId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column spreader.tb_content_replay.content_id
	 * 
	 * @param contentId
	 *            the value for spreader.tb_content_replay.content_id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column spreader.tb_content_replay.content
	 * 
	 * @return the value of spreader.tb_content_replay.content
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column spreader.tb_content_replay.content
	 * 
	 * @param content
	 *            the value for spreader.tb_content_replay.content
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column spreader.tb_content_replay.pub_date
	 * 
	 * @return the value of spreader.tb_content_replay.pub_date
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public Date getPubDate() {
		return pubDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column spreader.tb_content_replay.pub_date
	 * 
	 * @param pubDate
	 *            the value for spreader.tb_content_replay.pub_date
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column spreader.tb_content_replay.website_id
	 * 
	 * @return the value of spreader.tb_content_replay.website_id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public Integer getWebsiteId() {
		return websiteId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column spreader.tb_content_replay.website_id
	 * 
	 * @param websiteId
	 *            the value for spreader.tb_content_replay.website_id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public void setWebsiteId(Integer websiteId) {
		this.websiteId = websiteId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column spreader.tb_content_replay.ref_id
	 * 
	 * @return the value of spreader.tb_content_replay.ref_id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public Long getRefId() {
		return refId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column spreader.tb_content_replay.ref_id
	 * 
	 * @param refId
	 *            the value for spreader.tb_content_replay.ref_id
	 * 
	 * @ibatorgenerated Mon Jul 09 11:42:54 CST 2012
	 */
	public void setRefId(Long refId) {
		this.refId = refId;
	}

	public ContentReplay getRefReplay() {
		return refReplay;
	}

	public void setRefReplay(ContentReplay refReplay) {
		this.refReplay = refReplay;
	}

	public Content getRefContent() {
		return refContent;
	}

	public void setRefContent(Content refContent) {
		this.refContent = refContent;
	}
}
