package com.nali.spreader.data;

import com.nali.common.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class UserGroup extends BaseModel implements Serializable {

    private static final long serialVersionUID = -7272874364307869044L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_group.gid
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    private Long gid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_group.gname
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    private String gname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_group.description
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_group.gtype
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    private Integer gtype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_group.create_time
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_group.last_modified_time
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    private Date lastModifiedTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_group.website_id
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    private Integer websiteId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_group.prop_val
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    private Integer propVal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_user_group.prop_exp
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    private String propExp;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_group.gid
     *
     * @return the value of spreader.tb_user_group.gid
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public Long getGid() {
        return gid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_group.gid
     *
     * @param gid the value for spreader.tb_user_group.gid
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public void setGid(Long gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_group.gname
     *
     * @return the value of spreader.tb_user_group.gname
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_group.gname
     *
     * @param gname the value for spreader.tb_user_group.gname
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public void setGname(String gname) {
        this.gname = gname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_group.description
     *
     * @return the value of spreader.tb_user_group.description
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_group.description
     *
     * @param description the value for spreader.tb_user_group.description
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_group.gtype
     *
     * @return the value of spreader.tb_user_group.gtype
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public Integer getGtype() {
        return gtype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_group.gtype
     *
     * @param gtype the value for spreader.tb_user_group.gtype
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public void setGtype(Integer gtype) {
        this.gtype = gtype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_group.create_time
     *
     * @return the value of spreader.tb_user_group.create_time
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_group.create_time
     *
     * @param createTime the value for spreader.tb_user_group.create_time
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_group.last_modified_time
     *
     * @return the value of spreader.tb_user_group.last_modified_time
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_group.last_modified_time
     *
     * @param lastModifiedTime the value for spreader.tb_user_group.last_modified_time
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_group.website_id
     *
     * @return the value of spreader.tb_user_group.website_id
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_group.website_id
     *
     * @param websiteId the value for spreader.tb_user_group.website_id
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_group.prop_val
     *
     * @return the value of spreader.tb_user_group.prop_val
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public Integer getPropVal() {
        return propVal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_group.prop_val
     *
     * @param propVal the value for spreader.tb_user_group.prop_val
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public void setPropVal(Integer propVal) {
        this.propVal = propVal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_user_group.prop_exp
     *
     * @return the value of spreader.tb_user_group.prop_exp
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public String getPropExp() {
        return propExp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_user_group.prop_exp
     *
     * @param propExp the value for spreader.tb_user_group.prop_exp
     *
     * @ibatorgenerated Wed Jan 18 15:16:17 CST 2012
     */
    public void setPropExp(String propExp) {
        this.propExp = propExp;
    }
}
