package com.nali.spreader.dao;

import com.nali.spreader.model.ClientAction;
import com.nali.spreader.model.ClientActionExample;
import java.util.List;

public interface ICrudClientActionDao {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    int countByExample(ClientActionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    int deleteByExample(ClientActionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    void insert(ClientAction record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    void insertSelective(ClientAction record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    List<ClientAction> selectByExampleWithBLOBs(ClientActionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    List<ClientAction> selectByExampleWithoutBLOBs(ClientActionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    ClientAction selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    int updateByExampleSelective(ClientAction record, ClientActionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    int updateByExampleWithBLOBs(ClientAction record, ClientActionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    int updateByExampleWithoutBLOBs(ClientAction record, ClientActionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    int updateByPrimaryKeySelective(ClientAction record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    int updateByPrimaryKeyWithBLOBs(ClientAction record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_action
     *
     * @ibatorgenerated Wed Jul 20 16:30:56 CST 2011
     */
    int updateByPrimaryKeyWithoutBLOBs(ClientAction record);
}