package com.nali.spreader.dao;

import com.nali.spreader.model.ActionStep;
import com.nali.spreader.model.ActionStepExample;
import com.nali.spreader.model.TbActionStepWithBLOBs;
import java.util.List;

public interface ICrudActionStepDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    int countByExample(ActionStepExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    int deleteByExample(ActionStepExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    void insert(TbActionStepWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    void insertSelective(TbActionStepWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    List<TbActionStepWithBLOBs> selectByExampleWithBLOBs(ActionStepExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    List<ActionStep> selectByExampleWithoutBLOBs(ActionStepExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    TbActionStepWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    int updateByExampleSelective(TbActionStepWithBLOBs record, ActionStepExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    int updateByExample(TbActionStepWithBLOBs record, ActionStepExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    int updateByExample(ActionStep record, ActionStepExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    int updateByPrimaryKeySelective(TbActionStepWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    int updateByPrimaryKey(TbActionStepWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_action_step
     *
     * @ibatorgenerated Fri Jul 15 17:17:12 CST 2011
     */
    int updateByPrimaryKey(ActionStep record);
}
