package com.nali.spreader.dao;

import com.nali.spreader.model.LoginConfig;
import com.nali.spreader.model.LoginConfigExample;
import java.util.List;

public interface ICrudLoginConfigDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    int countByExample(LoginConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    int deleteByExample(LoginConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    void insert(LoginConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    void insertSelective(LoginConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    List<LoginConfig> selectByExampleWithBLOBs(LoginConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    List<LoginConfig> selectByExampleWithoutBLOBs(LoginConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    LoginConfig selectByPrimaryKey(Long uid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    int updateByExampleSelective(LoginConfig record, LoginConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    int updateByExampleWithBLOBs(LoginConfig record, LoginConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    int updateByExampleWithoutBLOBs(LoginConfig record, LoginConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    int updateByPrimaryKeySelective(LoginConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    int updateByPrimaryKeyWithBLOBs(LoginConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_login_config
     *
     * @ibatorgenerated Fri Jul 15 17:17:13 CST 2011
     */
    int updateByPrimaryKeyWithoutBLOBs(LoginConfig record);
}
