package com.nali.spreader.dao;

import com.nali.spreader.model.ClientConfig;
import com.nali.spreader.model.ClientConfigExample;
import java.util.List;

public interface ICrudClientConfigDao {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    int countByExample(ClientConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    int deleteByExample(ClientConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    Long insert(ClientConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    Long insertSelective(ClientConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    List<ClientConfig> selectByExample(ClientConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    ClientConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    int updateByExampleSelective(ClientConfig record, ClientConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    int updateByExample(ClientConfig record, ClientConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    int updateByPrimaryKeySelective(ClientConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_client_config
     *
     * @ibatorgenerated Thu Mar 07 13:32:56 CST 2013
     */
    int updateByPrimaryKey(ClientConfig record);
}