package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudRobotWeiboXimalayaDao;
import com.nali.spreader.data.RobotWeiboXimalaya;
import com.nali.spreader.data.RobotWeiboXimalayaExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudRobotWeiboXimalayaDao implements ICrudRobotWeiboXimalayaDao {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public CrudRobotWeiboXimalayaDao() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public int countByExample(RobotWeiboXimalayaExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public int deleteByExample(RobotWeiboXimalayaExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public int deleteByPrimaryKey(Long id) {
        RobotWeiboXimalaya key = new RobotWeiboXimalaya();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public Long insert(RobotWeiboXimalaya record) {
        Object newKey = getSqlMapClientTemplate().insert("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public Long insertSelective(RobotWeiboXimalaya record) {
        Object newKey = getSqlMapClientTemplate().insert("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<RobotWeiboXimalaya> selectByExample(RobotWeiboXimalayaExample example) {
        List<RobotWeiboXimalaya> list = getSqlMapClientTemplate().queryForList("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public RobotWeiboXimalaya selectByPrimaryKey(Long id) {
        RobotWeiboXimalaya key = new RobotWeiboXimalaya();
        key.setId(id);
        RobotWeiboXimalaya record = (RobotWeiboXimalaya) getSqlMapClientTemplate().queryForObject("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public int updateByExampleSelective(RobotWeiboXimalaya record, RobotWeiboXimalayaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public int updateByExample(RobotWeiboXimalaya record, RobotWeiboXimalayaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public int updateByPrimaryKeySelective(RobotWeiboXimalaya record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public int updateByPrimaryKey(RobotWeiboXimalaya record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_robot_weibo_ximalaya.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_robot_weibo_ximalaya
     *
     * @ibatorgenerated Tue Nov 27 16:16:33 CST 2012
     */
    private static class UpdateByExampleParms extends RobotWeiboXimalayaExample {
        private Object record;

        public UpdateByExampleParms(Object record, RobotWeiboXimalayaExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}