package com.nali.spreader.dao.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.stereotype.Repository;

import com.nali.spreader.dao.ICrudAppUdidDao;
import com.nali.spreader.data.AppUdid;
import com.nali.spreader.data.AppUdidExample;

@Repository
public class CrudAppUdidDao implements ICrudAppUdidDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Wed Jun 06 17:41:16 CST 2012
     */
    public CrudAppUdidDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public int countByExample(AppUdidExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_app_udid.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public int deleteByExample(AppUdidExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_app_udid.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public int deleteByPrimaryKey(Long registerId) {
        AppUdid key = new AppUdid();
        key.setRegisterId(registerId);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_app_udid.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public void insert(AppUdid record) {
        getSqlMapClientTemplate().insert("spreader_tb_app_udid.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public void insertSelective(AppUdid record) {
        getSqlMapClientTemplate().insert("spreader_tb_app_udid.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<AppUdid> selectByExample(AppUdidExample example) {
        List<AppUdid> list = getSqlMapClientTemplate().queryForList("spreader_tb_app_udid.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public AppUdid selectByPrimaryKey(Long registerId) {
        AppUdid key = new AppUdid();
        key.setRegisterId(registerId);
        AppUdid record = (AppUdid) getSqlMapClientTemplate().queryForObject("spreader_tb_app_udid.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public int updateByExampleSelective(AppUdid record, AppUdidExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_app_udid.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public int updateByExample(AppUdid record, AppUdidExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_app_udid.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public int updateByPrimaryKeySelective(AppUdid record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_app_udid.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public int updateByPrimaryKey(AppUdid record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_app_udid.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_app_udid
     *
     * @ibatorgenerated Mon Jul 02 15:18:29 CST 2012
     */
    private static class UpdateByExampleParms extends AppUdidExample {

        private Object record;

        public UpdateByExampleParms(Object record, AppUdidExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
