package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudContentCookiesDao;
import com.nali.spreader.model.ContentCookiesExample;
import com.nali.spreader.model.TbContentCookiesKey;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudContentCookiesDao implements ICrudContentCookiesDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Sun Mar 13 15:40:27 CST 2011
     */
    public CrudContentCookiesDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int countByExample(ContentCookiesExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_content_cookies.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int deleteByExample(ContentCookiesExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_content_cookies.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int deleteByPrimaryKey(TbContentCookiesKey key) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_content_cookies.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public void insert(TbContentCookiesKey record) {
        getSqlMapClientTemplate().insert("spreader_tb_content_cookies.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public void insertSelective(TbContentCookiesKey record) {
        getSqlMapClientTemplate().insert("spreader_tb_content_cookies.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public List selectByExample(ContentCookiesExample example) {
        List list = getSqlMapClientTemplate().queryForList("spreader_tb_content_cookies.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int updateByExampleSelective(TbContentCookiesKey record, ContentCookiesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_content_cookies.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int updateByExample(TbContentCookiesKey record, ContentCookiesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_content_cookies.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_content_cookies
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    private static class UpdateByExampleParms extends ContentCookiesExample {

        private Object record;

        public UpdateByExampleParms(Object record, ContentCookiesExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
