package com.nali.spreader.dao.impl;

import com.nali.spreader.dao.ICrudTargetTemplateParametersDao;
import com.nali.spreader.model.TargetTemplateParameters;
import com.nali.spreader.model.TargetTemplateParametersExample;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.SqlMapClientTemplate;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

@Repository
public class CrudTargetTemplateParametersDao implements ICrudTargetTemplateParametersDao {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Sat Mar 12 17:19:22 CST 2011
     */
    public CrudTargetTemplateParametersDao() {
        super();
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    @Autowired
    private SqlMapClientTemplate sqlMap;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int countByExample(TargetTemplateParametersExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("spreader_tb_target_template_parameters.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int deleteByExample(TargetTemplateParametersExample example) {
        int rows = getSqlMapClientTemplate().delete("spreader_tb_target_template_parameters.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int deleteByPrimaryKey(Long id) {
        TargetTemplateParameters key = new TargetTemplateParameters();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("spreader_tb_target_template_parameters.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public void insert(TargetTemplateParameters record) {
        getSqlMapClientTemplate().insert("spreader_tb_target_template_parameters.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public void insertSelective(TargetTemplateParameters record) {
        getSqlMapClientTemplate().insert("spreader_tb_target_template_parameters.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public List selectByExample(TargetTemplateParametersExample example) {
        List list = getSqlMapClientTemplate().queryForList("spreader_tb_target_template_parameters.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public TargetTemplateParameters selectByPrimaryKey(Long id) {
        TargetTemplateParameters key = new TargetTemplateParameters();
        key.setId(id);
        TargetTemplateParameters record = (TargetTemplateParameters) getSqlMapClientTemplate().queryForObject("spreader_tb_target_template_parameters.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int updateByExampleSelective(TargetTemplateParameters record, TargetTemplateParametersExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_target_template_parameters.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int updateByExample(TargetTemplateParameters record, TargetTemplateParametersExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("spreader_tb_target_template_parameters.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int updateByPrimaryKeySelective(TargetTemplateParameters record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_target_template_parameters.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public int updateByPrimaryKey(TargetTemplateParameters record) {
        int rows = getSqlMapClientTemplate().update("spreader_tb_target_template_parameters.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public SqlMapClientTemplate getSqlMapClientTemplate() {
        return sqlMap;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_target_template_parameters
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    private static class UpdateByExampleParms extends TargetTemplateParametersExample {

        private Object record;

        public UpdateByExampleParms(Object record, TargetTemplateParametersExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
