package com.nali.spreader.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;
import com.nali.common.model.BaseModel;

/**
 * ClientTask<br>&nbsp;
 * @author sam Created on 2011-8-1
 */
public class ClientTask extends BaseModel implements Serializable {

    private static final long serialVersionUID = 5144184626459560630L;

    public static final Long DEFAULT_BATCH_ID = 0L;
    public static final Integer STATUS_READY = 0;
    public static final Integer STATUS_ASSIGNED = 1;

    private Map<String, Object> contentObjects;

    public Map<String, Object> getContentObjects() {
        return contentObjects;
    }

    public void setContentObjects(Map<String, Object> contentObjects) {
        this.contentObjects = contentObjects;
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.id
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.action_id
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private Long actionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.uid
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private Long uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.task_code
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private String taskCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.batch_id
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private Long batchId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.task_type
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private Integer taskType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.expire_time
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private Date expireTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.base_priority
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private Integer basePriority;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.start_time
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private Date startTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.priority
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private Long priority;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.status
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column spreader.tb_client_task.contents
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    private String contents;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.id
     *
     * @return the value of spreader.tb_client_task.id
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.id
     *
     * @param id the value for spreader.tb_client_task.id
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.action_id
     *
     * @return the value of spreader.tb_client_task.action_id
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public Long getActionId() {
        return actionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.action_id
     *
     * @param actionId the value for spreader.tb_client_task.action_id
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setActionId(Long actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.uid
     *
     * @return the value of spreader.tb_client_task.uid
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.uid
     *
     * @param uid the value for spreader.tb_client_task.uid
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.task_code
     *
     * @return the value of spreader.tb_client_task.task_code
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.task_code
     *
     * @param taskCode the value for spreader.tb_client_task.task_code
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.batch_id
     *
     * @return the value of spreader.tb_client_task.batch_id
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public Long getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.batch_id
     *
     * @param batchId the value for spreader.tb_client_task.batch_id
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setBatchId(Long batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.task_type
     *
     * @return the value of spreader.tb_client_task.task_type
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.task_type
     *
     * @param taskType the value for spreader.tb_client_task.task_type
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.expire_time
     *
     * @return the value of spreader.tb_client_task.expire_time
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.expire_time
     *
     * @param expireTime the value for spreader.tb_client_task.expire_time
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.base_priority
     *
     * @return the value of spreader.tb_client_task.base_priority
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public Integer getBasePriority() {
        return basePriority;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.base_priority
     *
     * @param basePriority the value for spreader.tb_client_task.base_priority
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setBasePriority(Integer basePriority) {
        this.basePriority = basePriority;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.start_time
     *
     * @return the value of spreader.tb_client_task.start_time
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.start_time
     *
     * @param startTime the value for spreader.tb_client_task.start_time
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.priority
     *
     * @return the value of spreader.tb_client_task.priority
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public Long getPriority() {
        return priority;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.priority
     *
     * @param priority the value for spreader.tb_client_task.priority
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setPriority(Long priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.status
     *
     * @return the value of spreader.tb_client_task.status
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.status
     *
     * @param status the value for spreader.tb_client_task.status
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column spreader.tb_client_task.contents
     *
     * @return the value of spreader.tb_client_task.contents
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column spreader.tb_client_task.contents
     *
     * @param contents the value for spreader.tb_client_task.contents
     *
     * @ibatorgenerated Sat Feb 11 15:42:16 CST 2012
     */
    public void setContents(String contents) {
        this.contents = contents;
    }
}
