package com.nali.spreader.model;

import com.nali.common.model.Limit;
import com.nali.common.model.Shard;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CompositeTaskExample {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Sun Mar 13 15:40:27 CST 2011
     */
    public CompositeTaskExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Sun Mar 13 15:40:27 CST 2011
     */
    protected CompositeTaskExample(CompositeTaskExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.limit = example.limit;
        this.shard = example.shard;
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    private Shard shard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    private Limit limit;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public void setShard(Shard shard) {
        this.shard = shard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public void setLimit(Limit limit) {
        this.limit = limit;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table spreader.tb_composite_task
     *
     * @ibatorgenerated Thu Mar 31 15:39:48 CST 2011
     */
    public static class Criteria {

        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("client_id is null");
            return this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("client_id is not null");
            return this;
        }

        public Criteria andClientIdEqualTo(Integer value) {
            addCriterion("client_id =", value, "clientId");
            return this;
        }

        public Criteria andClientIdNotEqualTo(Integer value) {
            addCriterion("client_id <>", value, "clientId");
            return this;
        }

        public Criteria andClientIdGreaterThan(Integer value) {
            addCriterion("client_id >", value, "clientId");
            return this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("client_id >=", value, "clientId");
            return this;
        }

        public Criteria andClientIdLessThan(Integer value) {
            addCriterion("client_id <", value, "clientId");
            return this;
        }

        public Criteria andClientIdLessThanOrEqualTo(Integer value) {
            addCriterion("client_id <=", value, "clientId");
            return this;
        }

        public Criteria andClientIdIn(List values) {
            addCriterion("client_id in", values, "clientId");
            return this;
        }

        public Criteria andClientIdNotIn(List values) {
            addCriterion("client_id not in", values, "clientId");
            return this;
        }

        public Criteria andClientIdBetween(Integer value1, Integer value2) {
            addCriterion("client_id between", value1, value2, "clientId");
            return this;
        }

        public Criteria andClientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("client_id not between", value1, value2, "clientId");
            return this;
        }

        public Criteria andErrorReasonIsNull() {
            addCriterion("error_reason is null");
            return this;
        }

        public Criteria andErrorReasonIsNotNull() {
            addCriterion("error_reason is not null");
            return this;
        }

        public Criteria andErrorReasonEqualTo(String value) {
            addCriterion("error_reason =", value, "errorReason");
            return this;
        }

        public Criteria andErrorReasonNotEqualTo(String value) {
            addCriterion("error_reason <>", value, "errorReason");
            return this;
        }

        public Criteria andErrorReasonGreaterThan(String value) {
            addCriterion("error_reason >", value, "errorReason");
            return this;
        }

        public Criteria andErrorReasonGreaterThanOrEqualTo(String value) {
            addCriterion("error_reason >=", value, "errorReason");
            return this;
        }

        public Criteria andErrorReasonLessThan(String value) {
            addCriterion("error_reason <", value, "errorReason");
            return this;
        }

        public Criteria andErrorReasonLessThanOrEqualTo(String value) {
            addCriterion("error_reason <=", value, "errorReason");
            return this;
        }

        public Criteria andErrorReasonLike(String value) {
            addCriterion("error_reason like", value, "errorReason");
            return this;
        }

        public Criteria andErrorReasonNotLike(String value) {
            addCriterion("error_reason not like", value, "errorReason");
            return this;
        }

        public Criteria andErrorReasonIn(List values) {
            addCriterion("error_reason in", values, "errorReason");
            return this;
        }

        public Criteria andErrorReasonNotIn(List values) {
            addCriterion("error_reason not in", values, "errorReason");
            return this;
        }

        public Criteria andErrorReasonBetween(String value1, String value2) {
            addCriterion("error_reason between", value1, value2, "errorReason");
            return this;
        }

        public Criteria andErrorReasonNotBetween(String value1, String value2) {
            addCriterion("error_reason not between", value1, value2, "errorReason");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("user_id in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("user_id not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeIn(List values) {
            addCriterion("created_time in", values, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeNotIn(List values) {
            addCriterion("created_time not in", values, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return this;
        }

        public Criteria andCheckUrlIsNull() {
            addCriterion("check_url is null");
            return this;
        }

        public Criteria andCheckUrlIsNotNull() {
            addCriterion("check_url is not null");
            return this;
        }

        public Criteria andCheckUrlEqualTo(String value) {
            addCriterion("check_url =", value, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlNotEqualTo(String value) {
            addCriterion("check_url <>", value, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlGreaterThan(String value) {
            addCriterion("check_url >", value, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlGreaterThanOrEqualTo(String value) {
            addCriterion("check_url >=", value, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlLessThan(String value) {
            addCriterion("check_url <", value, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlLessThanOrEqualTo(String value) {
            addCriterion("check_url <=", value, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlLike(String value) {
            addCriterion("check_url like", value, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlNotLike(String value) {
            addCriterion("check_url not like", value, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlIn(List values) {
            addCriterion("check_url in", values, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlNotIn(List values) {
            addCriterion("check_url not in", values, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlBetween(String value1, String value2) {
            addCriterion("check_url between", value1, value2, "checkUrl");
            return this;
        }

        public Criteria andCheckUrlNotBetween(String value1, String value2) {
            addCriterion("check_url not between", value1, value2, "checkUrl");
            return this;
        }

        public Criteria andWebsiteIdIsNull() {
            addCriterion("website_id is null");
            return this;
        }

        public Criteria andWebsiteIdIsNotNull() {
            addCriterion("website_id is not null");
            return this;
        }

        public Criteria andWebsiteIdEqualTo(Integer value) {
            addCriterion("website_id =", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdNotEqualTo(Integer value) {
            addCriterion("website_id <>", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdGreaterThan(Integer value) {
            addCriterion("website_id >", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("website_id >=", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdLessThan(Integer value) {
            addCriterion("website_id <", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdLessThanOrEqualTo(Integer value) {
            addCriterion("website_id <=", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdIn(List values) {
            addCriterion("website_id in", values, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdNotIn(List values) {
            addCriterion("website_id not in", values, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdBetween(Integer value1, Integer value2) {
            addCriterion("website_id between", value1, value2, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("website_id not between", value1, value2, "websiteId");
            return this;
        }

        public Criteria andUseCookieIsNull() {
            addCriterion("use_cookie is null");
            return this;
        }

        public Criteria andUseCookieIsNotNull() {
            addCriterion("use_cookie is not null");
            return this;
        }

        public Criteria andUseCookieEqualTo(Byte value) {
            addCriterion("use_cookie =", value, "useCookie");
            return this;
        }

        public Criteria andUseCookieNotEqualTo(Byte value) {
            addCriterion("use_cookie <>", value, "useCookie");
            return this;
        }

        public Criteria andUseCookieGreaterThan(Byte value) {
            addCriterion("use_cookie >", value, "useCookie");
            return this;
        }

        public Criteria andUseCookieGreaterThanOrEqualTo(Byte value) {
            addCriterion("use_cookie >=", value, "useCookie");
            return this;
        }

        public Criteria andUseCookieLessThan(Byte value) {
            addCriterion("use_cookie <", value, "useCookie");
            return this;
        }

        public Criteria andUseCookieLessThanOrEqualTo(Byte value) {
            addCriterion("use_cookie <=", value, "useCookie");
            return this;
        }

        public Criteria andUseCookieIn(List values) {
            addCriterion("use_cookie in", values, "useCookie");
            return this;
        }

        public Criteria andUseCookieNotIn(List values) {
            addCriterion("use_cookie not in", values, "useCookie");
            return this;
        }

        public Criteria andUseCookieBetween(Byte value1, Byte value2) {
            addCriterion("use_cookie between", value1, value2, "useCookie");
            return this;
        }

        public Criteria andUseCookieNotBetween(Byte value1, Byte value2) {
            addCriterion("use_cookie not between", value1, value2, "useCookie");
            return this;
        }

        public Criteria andFlowIdIsNull() {
            addCriterion("flow_id is null");
            return this;
        }

        public Criteria andFlowIdIsNotNull() {
            addCriterion("flow_id is not null");
            return this;
        }

        public Criteria andFlowIdEqualTo(Long value) {
            addCriterion("flow_id =", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotEqualTo(Long value) {
            addCriterion("flow_id <>", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThan(Long value) {
            addCriterion("flow_id >", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThanOrEqualTo(Long value) {
            addCriterion("flow_id >=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThan(Long value) {
            addCriterion("flow_id <", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThanOrEqualTo(Long value) {
            addCriterion("flow_id <=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdIn(List values) {
            addCriterion("flow_id in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdNotIn(List values) {
            addCriterion("flow_id not in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdBetween(Long value1, Long value2) {
            addCriterion("flow_id between", value1, value2, "flowId");
            return this;
        }

        public Criteria andFlowIdNotBetween(Long value1, Long value2) {
            addCriterion("flow_id not between", value1, value2, "flowId");
            return this;
        }
    }
}
