package com.nali.spreader.model;

import com.nali.common.model.Limit;
import com.nali.common.model.Shard;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RealUserExample {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_real_user
     *
     * @ibatorgenerated Sat Mar 12 17:16:39 CST 2011
     */
    public RealUserExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table spreader.tb_real_user
     *
     * @ibatorgenerated Sat Mar 12 17:16:39 CST 2011
     */
    protected RealUserExample(RealUserExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.limit = example.limit;
        this.shard = example.shard;
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    protected List oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    private Shard shard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    private Limit limit;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    public void setShard(Shard shard) {
        this.shard = shard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    public void setLimit(Limit limit) {
        this.limit = limit;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ebuy.tb_real_user
     *
     * @ibatorgenerated Fri Mar 25 19:27:43 CST 2011
     */
    public static class Criteria {

        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return this;
        }

        public Criteria andUidEqualTo(Long value) {
            addCriterion("uid =", value, "uid");
            return this;
        }

        public Criteria andUidNotEqualTo(Long value) {
            addCriterion("uid <>", value, "uid");
            return this;
        }

        public Criteria andUidGreaterThan(Long value) {
            addCriterion("uid >", value, "uid");
            return this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Long value) {
            addCriterion("uid >=", value, "uid");
            return this;
        }

        public Criteria andUidLessThan(Long value) {
            addCriterion("uid <", value, "uid");
            return this;
        }

        public Criteria andUidLessThanOrEqualTo(Long value) {
            addCriterion("uid <=", value, "uid");
            return this;
        }

        public Criteria andUidIn(List values) {
            addCriterion("uid in", values, "uid");
            return this;
        }

        public Criteria andUidNotIn(List values) {
            addCriterion("uid not in", values, "uid");
            return this;
        }

        public Criteria andUidBetween(Long value1, Long value2) {
            addCriterion("uid between", value1, value2, "uid");
            return this;
        }

        public Criteria andUidNotBetween(Long value1, Long value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return this;
        }

        public Criteria andWebsiteUidIsNull() {
            addCriterion("website_uid is null");
            return this;
        }

        public Criteria andWebsiteUidIsNotNull() {
            addCriterion("website_uid is not null");
            return this;
        }

        public Criteria andWebsiteUidEqualTo(Long value) {
            addCriterion("website_uid =", value, "websiteUid");
            return this;
        }

        public Criteria andWebsiteUidNotEqualTo(Long value) {
            addCriterion("website_uid <>", value, "websiteUid");
            return this;
        }

        public Criteria andWebsiteUidGreaterThan(Long value) {
            addCriterion("website_uid >", value, "websiteUid");
            return this;
        }

        public Criteria andWebsiteUidGreaterThanOrEqualTo(Long value) {
            addCriterion("website_uid >=", value, "websiteUid");
            return this;
        }

        public Criteria andWebsiteUidLessThan(Long value) {
            addCriterion("website_uid <", value, "websiteUid");
            return this;
        }

        public Criteria andWebsiteUidLessThanOrEqualTo(Long value) {
            addCriterion("website_uid <=", value, "websiteUid");
            return this;
        }

        public Criteria andWebsiteUidIn(List values) {
            addCriterion("website_uid in", values, "websiteUid");
            return this;
        }

        public Criteria andWebsiteUidNotIn(List values) {
            addCriterion("website_uid not in", values, "websiteUid");
            return this;
        }

        public Criteria andWebsiteUidBetween(Long value1, Long value2) {
            addCriterion("website_uid between", value1, value2, "websiteUid");
            return this;
        }

        public Criteria andWebsiteUidNotBetween(Long value1, Long value2) {
            addCriterion("website_uid not between", value1, value2, "websiteUid");
            return this;
        }

        public Criteria andWebsiteIdIsNull() {
            addCriterion("website_id is null");
            return this;
        }

        public Criteria andWebsiteIdIsNotNull() {
            addCriterion("website_id is not null");
            return this;
        }

        public Criteria andWebsiteIdEqualTo(Integer value) {
            addCriterion("website_id =", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdNotEqualTo(Integer value) {
            addCriterion("website_id <>", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdGreaterThan(Integer value) {
            addCriterion("website_id >", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("website_id >=", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdLessThan(Integer value) {
            addCriterion("website_id <", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdLessThanOrEqualTo(Integer value) {
            addCriterion("website_id <=", value, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdIn(List values) {
            addCriterion("website_id in", values, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdNotIn(List values) {
            addCriterion("website_id not in", values, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdBetween(Integer value1, Integer value2) {
            addCriterion("website_id between", value1, value2, "websiteId");
            return this;
        }

        public Criteria andWebsiteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("website_id not between", value1, value2, "websiteId");
            return this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return this;
        }

        public Criteria andUserNameIn(List values) {
            addCriterion("user_name in", values, "userName");
            return this;
        }

        public Criteria andUserNameNotIn(List values) {
            addCriterion("user_name not in", values, "userName");
            return this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List values) {
            addCriterion("email in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List values) {
            addCriterion("email not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return this;
        }

        public Criteria andNationalityIsNull() {
            addCriterion("nationality is null");
            return this;
        }

        public Criteria andNationalityIsNotNull() {
            addCriterion("nationality is not null");
            return this;
        }

        public Criteria andNationalityEqualTo(String value) {
            addCriterion("nationality =", value, "nationality");
            return this;
        }

        public Criteria andNationalityNotEqualTo(String value) {
            addCriterion("nationality <>", value, "nationality");
            return this;
        }

        public Criteria andNationalityGreaterThan(String value) {
            addCriterion("nationality >", value, "nationality");
            return this;
        }

        public Criteria andNationalityGreaterThanOrEqualTo(String value) {
            addCriterion("nationality >=", value, "nationality");
            return this;
        }

        public Criteria andNationalityLessThan(String value) {
            addCriterion("nationality <", value, "nationality");
            return this;
        }

        public Criteria andNationalityLessThanOrEqualTo(String value) {
            addCriterion("nationality <=", value, "nationality");
            return this;
        }

        public Criteria andNationalityLike(String value) {
            addCriterion("nationality like", value, "nationality");
            return this;
        }

        public Criteria andNationalityNotLike(String value) {
            addCriterion("nationality not like", value, "nationality");
            return this;
        }

        public Criteria andNationalityIn(List values) {
            addCriterion("nationality in", values, "nationality");
            return this;
        }

        public Criteria andNationalityNotIn(List values) {
            addCriterion("nationality not in", values, "nationality");
            return this;
        }

        public Criteria andNationalityBetween(String value1, String value2) {
            addCriterion("nationality between", value1, value2, "nationality");
            return this;
        }

        public Criteria andNationalityNotBetween(String value1, String value2) {
            addCriterion("nationality not between", value1, value2, "nationality");
            return this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return this;
        }

        public Criteria andProvinceIn(List values) {
            addCriterion("province in", values, "province");
            return this;
        }

        public Criteria andProvinceNotIn(List values) {
            addCriterion("province not in", values, "province");
            return this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return this;
        }

        public Criteria andCityIn(List values) {
            addCriterion("city in", values, "city");
            return this;
        }

        public Criteria andCityNotIn(List values) {
            addCriterion("city not in", values, "city");
            return this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return this;
        }

        public Criteria andDistrictIsNull() {
            addCriterion("district is null");
            return this;
        }

        public Criteria andDistrictIsNotNull() {
            addCriterion("district is not null");
            return this;
        }

        public Criteria andDistrictEqualTo(String value) {
            addCriterion("district =", value, "district");
            return this;
        }

        public Criteria andDistrictNotEqualTo(String value) {
            addCriterion("district <>", value, "district");
            return this;
        }

        public Criteria andDistrictGreaterThan(String value) {
            addCriterion("district >", value, "district");
            return this;
        }

        public Criteria andDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("district >=", value, "district");
            return this;
        }

        public Criteria andDistrictLessThan(String value) {
            addCriterion("district <", value, "district");
            return this;
        }

        public Criteria andDistrictLessThanOrEqualTo(String value) {
            addCriterion("district <=", value, "district");
            return this;
        }

        public Criteria andDistrictLike(String value) {
            addCriterion("district like", value, "district");
            return this;
        }

        public Criteria andDistrictNotLike(String value) {
            addCriterion("district not like", value, "district");
            return this;
        }

        public Criteria andDistrictIn(List values) {
            addCriterion("district in", values, "district");
            return this;
        }

        public Criteria andDistrictNotIn(List values) {
            addCriterion("district not in", values, "district");
            return this;
        }

        public Criteria andDistrictBetween(String value1, String value2) {
            addCriterion("district between", value1, value2, "district");
            return this;
        }

        public Criteria andDistrictNotBetween(String value1, String value2) {
            addCriterion("district not between", value1, value2, "district");
            return this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return this;
        }

        public Criteria andSexEqualTo(Byte value) {
            addCriterion("sex =", value, "sex");
            return this;
        }

        public Criteria andSexNotEqualTo(Byte value) {
            addCriterion("sex <>", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThan(Byte value) {
            addCriterion("sex >", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Byte value) {
            addCriterion("sex >=", value, "sex");
            return this;
        }

        public Criteria andSexLessThan(Byte value) {
            addCriterion("sex <", value, "sex");
            return this;
        }

        public Criteria andSexLessThanOrEqualTo(Byte value) {
            addCriterion("sex <=", value, "sex");
            return this;
        }

        public Criteria andSexIn(List values) {
            addCriterion("sex in", values, "sex");
            return this;
        }

        public Criteria andSexNotIn(List values) {
            addCriterion("sex not in", values, "sex");
            return this;
        }

        public Criteria andSexBetween(Byte value1, Byte value2) {
            addCriterion("sex between", value1, value2, "sex");
            return this;
        }

        public Criteria andSexNotBetween(Byte value1, Byte value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return this;
        }

        public Criteria andQqIsNull() {
            addCriterion("qq is null");
            return this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("qq is not null");
            return this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("qq =", value, "qq");
            return this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("qq <>", value, "qq");
            return this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("qq >", value, "qq");
            return this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("qq >=", value, "qq");
            return this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("qq <", value, "qq");
            return this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("qq <=", value, "qq");
            return this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("qq like", value, "qq");
            return this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("qq not like", value, "qq");
            return this;
        }

        public Criteria andQqIn(List values) {
            addCriterion("qq in", values, "qq");
            return this;
        }

        public Criteria andQqNotIn(List values) {
            addCriterion("qq not in", values, "qq");
            return this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("qq between", value1, value2, "qq");
            return this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("qq not between", value1, value2, "qq");
            return this;
        }

        public Criteria andMsnIsNull() {
            addCriterion("msn is null");
            return this;
        }

        public Criteria andMsnIsNotNull() {
            addCriterion("msn is not null");
            return this;
        }

        public Criteria andMsnEqualTo(String value) {
            addCriterion("msn =", value, "msn");
            return this;
        }

        public Criteria andMsnNotEqualTo(String value) {
            addCriterion("msn <>", value, "msn");
            return this;
        }

        public Criteria andMsnGreaterThan(String value) {
            addCriterion("msn >", value, "msn");
            return this;
        }

        public Criteria andMsnGreaterThanOrEqualTo(String value) {
            addCriterion("msn >=", value, "msn");
            return this;
        }

        public Criteria andMsnLessThan(String value) {
            addCriterion("msn <", value, "msn");
            return this;
        }

        public Criteria andMsnLessThanOrEqualTo(String value) {
            addCriterion("msn <=", value, "msn");
            return this;
        }

        public Criteria andMsnLike(String value) {
            addCriterion("msn like", value, "msn");
            return this;
        }

        public Criteria andMsnNotLike(String value) {
            addCriterion("msn not like", value, "msn");
            return this;
        }

        public Criteria andMsnIn(List values) {
            addCriterion("msn in", values, "msn");
            return this;
        }

        public Criteria andMsnNotIn(List values) {
            addCriterion("msn not in", values, "msn");
            return this;
        }

        public Criteria andMsnBetween(String value1, String value2) {
            addCriterion("msn between", value1, value2, "msn");
            return this;
        }

        public Criteria andMsnNotBetween(String value1, String value2) {
            addCriterion("msn not between", value1, value2, "msn");
            return this;
        }

        public Criteria andNickNameIsNull() {
            addCriterion("nick_name is null");
            return this;
        }

        public Criteria andNickNameIsNotNull() {
            addCriterion("nick_name is not null");
            return this;
        }

        public Criteria andNickNameEqualTo(String value) {
            addCriterion("nick_name =", value, "nickName");
            return this;
        }

        public Criteria andNickNameNotEqualTo(String value) {
            addCriterion("nick_name <>", value, "nickName");
            return this;
        }

        public Criteria andNickNameGreaterThan(String value) {
            addCriterion("nick_name >", value, "nickName");
            return this;
        }

        public Criteria andNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("nick_name >=", value, "nickName");
            return this;
        }

        public Criteria andNickNameLessThan(String value) {
            addCriterion("nick_name <", value, "nickName");
            return this;
        }

        public Criteria andNickNameLessThanOrEqualTo(String value) {
            addCriterion("nick_name <=", value, "nickName");
            return this;
        }

        public Criteria andNickNameLike(String value) {
            addCriterion("nick_name like", value, "nickName");
            return this;
        }

        public Criteria andNickNameNotLike(String value) {
            addCriterion("nick_name not like", value, "nickName");
            return this;
        }

        public Criteria andNickNameIn(List values) {
            addCriterion("nick_name in", values, "nickName");
            return this;
        }

        public Criteria andNickNameNotIn(List values) {
            addCriterion("nick_name not in", values, "nickName");
            return this;
        }

        public Criteria andNickNameBetween(String value1, String value2) {
            addCriterion("nick_name between", value1, value2, "nickName");
            return this;
        }

        public Criteria andNickNameNotBetween(String value1, String value2) {
            addCriterion("nick_name not between", value1, value2, "nickName");
            return this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("real_name is null");
            return this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("real_name is not null");
            return this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("real_name =", value, "realName");
            return this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("real_name <>", value, "realName");
            return this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("real_name >", value, "realName");
            return this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("real_name >=", value, "realName");
            return this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("real_name <", value, "realName");
            return this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("real_name <=", value, "realName");
            return this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("real_name like", value, "realName");
            return this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("real_name not like", value, "realName");
            return this;
        }

        public Criteria andRealNameIn(List values) {
            addCriterion("real_name in", values, "realName");
            return this;
        }

        public Criteria andRealNameNotIn(List values) {
            addCriterion("real_name not in", values, "realName");
            return this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("real_name between", value1, value2, "realName");
            return this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("real_name not between", value1, value2, "realName");
            return this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return this;
        }

        public Criteria andIdCardIn(List values) {
            addCriterion("id_card in", values, "idCard");
            return this;
        }

        public Criteria andIdCardNotIn(List values) {
            addCriterion("id_card not in", values, "idCard");
            return this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return this;
        }

        public Criteria andBirthdayYearIsNull() {
            addCriterion("birthday_year is null");
            return this;
        }

        public Criteria andBirthdayYearIsNotNull() {
            addCriterion("birthday_year is not null");
            return this;
        }

        public Criteria andBirthdayYearEqualTo(Integer value) {
            addCriterion("birthday_year =", value, "birthdayYear");
            return this;
        }

        public Criteria andBirthdayYearNotEqualTo(Integer value) {
            addCriterion("birthday_year <>", value, "birthdayYear");
            return this;
        }

        public Criteria andBirthdayYearGreaterThan(Integer value) {
            addCriterion("birthday_year >", value, "birthdayYear");
            return this;
        }

        public Criteria andBirthdayYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("birthday_year >=", value, "birthdayYear");
            return this;
        }

        public Criteria andBirthdayYearLessThan(Integer value) {
            addCriterion("birthday_year <", value, "birthdayYear");
            return this;
        }

        public Criteria andBirthdayYearLessThanOrEqualTo(Integer value) {
            addCriterion("birthday_year <=", value, "birthdayYear");
            return this;
        }

        public Criteria andBirthdayYearIn(List values) {
            addCriterion("birthday_year in", values, "birthdayYear");
            return this;
        }

        public Criteria andBirthdayYearNotIn(List values) {
            addCriterion("birthday_year not in", values, "birthdayYear");
            return this;
        }

        public Criteria andBirthdayYearBetween(Integer value1, Integer value2) {
            addCriterion("birthday_year between", value1, value2, "birthdayYear");
            return this;
        }

        public Criteria andBirthdayYearNotBetween(Integer value1, Integer value2) {
            addCriterion("birthday_year not between", value1, value2, "birthdayYear");
            return this;
        }

        public Criteria andBirthdayMonthIsNull() {
            addCriterion("birthday_month is null");
            return this;
        }

        public Criteria andBirthdayMonthIsNotNull() {
            addCriterion("birthday_month is not null");
            return this;
        }

        public Criteria andBirthdayMonthEqualTo(Integer value) {
            addCriterion("birthday_month =", value, "birthdayMonth");
            return this;
        }

        public Criteria andBirthdayMonthNotEqualTo(Integer value) {
            addCriterion("birthday_month <>", value, "birthdayMonth");
            return this;
        }

        public Criteria andBirthdayMonthGreaterThan(Integer value) {
            addCriterion("birthday_month >", value, "birthdayMonth");
            return this;
        }

        public Criteria andBirthdayMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("birthday_month >=", value, "birthdayMonth");
            return this;
        }

        public Criteria andBirthdayMonthLessThan(Integer value) {
            addCriterion("birthday_month <", value, "birthdayMonth");
            return this;
        }

        public Criteria andBirthdayMonthLessThanOrEqualTo(Integer value) {
            addCriterion("birthday_month <=", value, "birthdayMonth");
            return this;
        }

        public Criteria andBirthdayMonthIn(List values) {
            addCriterion("birthday_month in", values, "birthdayMonth");
            return this;
        }

        public Criteria andBirthdayMonthNotIn(List values) {
            addCriterion("birthday_month not in", values, "birthdayMonth");
            return this;
        }

        public Criteria andBirthdayMonthBetween(Integer value1, Integer value2) {
            addCriterion("birthday_month between", value1, value2, "birthdayMonth");
            return this;
        }

        public Criteria andBirthdayMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("birthday_month not between", value1, value2, "birthdayMonth");
            return this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return this;
        }

        public Criteria andCompanyNameIn(List values) {
            addCriterion("company_name in", values, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotIn(List values) {
            addCriterion("company_name not in", values, "companyName");
            return this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return this;
        }

        public Criteria andCompanyAddressIsNull() {
            addCriterion("company_address is null");
            return this;
        }

        public Criteria andCompanyAddressIsNotNull() {
            addCriterion("company_address is not null");
            return this;
        }

        public Criteria andCompanyAddressEqualTo(String value) {
            addCriterion("company_address =", value, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressNotEqualTo(String value) {
            addCriterion("company_address <>", value, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressGreaterThan(String value) {
            addCriterion("company_address >", value, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressGreaterThanOrEqualTo(String value) {
            addCriterion("company_address >=", value, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressLessThan(String value) {
            addCriterion("company_address <", value, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressLessThanOrEqualTo(String value) {
            addCriterion("company_address <=", value, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressLike(String value) {
            addCriterion("company_address like", value, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressNotLike(String value) {
            addCriterion("company_address not like", value, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressIn(List values) {
            addCriterion("company_address in", values, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressNotIn(List values) {
            addCriterion("company_address not in", values, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressBetween(String value1, String value2) {
            addCriterion("company_address between", value1, value2, "companyAddress");
            return this;
        }

        public Criteria andCompanyAddressNotBetween(String value1, String value2) {
            addCriterion("company_address not between", value1, value2, "companyAddress");
            return this;
        }

        public Criteria andHomeAddressIsNull() {
            addCriterion("home_address is null");
            return this;
        }

        public Criteria andHomeAddressIsNotNull() {
            addCriterion("home_address is not null");
            return this;
        }

        public Criteria andHomeAddressEqualTo(String value) {
            addCriterion("home_address =", value, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressNotEqualTo(String value) {
            addCriterion("home_address <>", value, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressGreaterThan(String value) {
            addCriterion("home_address >", value, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressGreaterThanOrEqualTo(String value) {
            addCriterion("home_address >=", value, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressLessThan(String value) {
            addCriterion("home_address <", value, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressLessThanOrEqualTo(String value) {
            addCriterion("home_address <=", value, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressLike(String value) {
            addCriterion("home_address like", value, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressNotLike(String value) {
            addCriterion("home_address not like", value, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressIn(List values) {
            addCriterion("home_address in", values, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressNotIn(List values) {
            addCriterion("home_address not in", values, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressBetween(String value1, String value2) {
            addCriterion("home_address between", value1, value2, "homeAddress");
            return this;
        }

        public Criteria andHomeAddressNotBetween(String value1, String value2) {
            addCriterion("home_address not between", value1, value2, "homeAddress");
            return this;
        }

        public Criteria andUniversityIsNull() {
            addCriterion("university is null");
            return this;
        }

        public Criteria andUniversityIsNotNull() {
            addCriterion("university is not null");
            return this;
        }

        public Criteria andUniversityEqualTo(String value) {
            addCriterion("university =", value, "university");
            return this;
        }

        public Criteria andUniversityNotEqualTo(String value) {
            addCriterion("university <>", value, "university");
            return this;
        }

        public Criteria andUniversityGreaterThan(String value) {
            addCriterion("university >", value, "university");
            return this;
        }

        public Criteria andUniversityGreaterThanOrEqualTo(String value) {
            addCriterion("university >=", value, "university");
            return this;
        }

        public Criteria andUniversityLessThan(String value) {
            addCriterion("university <", value, "university");
            return this;
        }

        public Criteria andUniversityLessThanOrEqualTo(String value) {
            addCriterion("university <=", value, "university");
            return this;
        }

        public Criteria andUniversityLike(String value) {
            addCriterion("university like", value, "university");
            return this;
        }

        public Criteria andUniversityNotLike(String value) {
            addCriterion("university not like", value, "university");
            return this;
        }

        public Criteria andUniversityIn(List values) {
            addCriterion("university in", values, "university");
            return this;
        }

        public Criteria andUniversityNotIn(List values) {
            addCriterion("university not in", values, "university");
            return this;
        }

        public Criteria andUniversityBetween(String value1, String value2) {
            addCriterion("university between", value1, value2, "university");
            return this;
        }

        public Criteria andUniversityNotBetween(String value1, String value2) {
            addCriterion("university not between", value1, value2, "university");
            return this;
        }

        public Criteria andJuniorMiddleSchoolIsNull() {
            addCriterion("junior_middle_school is null");
            return this;
        }

        public Criteria andJuniorMiddleSchoolIsNotNull() {
            addCriterion("junior_middle_school is not null");
            return this;
        }

        public Criteria andJuniorMiddleSchoolEqualTo(String value) {
            addCriterion("junior_middle_school =", value, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolNotEqualTo(String value) {
            addCriterion("junior_middle_school <>", value, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolGreaterThan(String value) {
            addCriterion("junior_middle_school >", value, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("junior_middle_school >=", value, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolLessThan(String value) {
            addCriterion("junior_middle_school <", value, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolLessThanOrEqualTo(String value) {
            addCriterion("junior_middle_school <=", value, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolLike(String value) {
            addCriterion("junior_middle_school like", value, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolNotLike(String value) {
            addCriterion("junior_middle_school not like", value, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolIn(List values) {
            addCriterion("junior_middle_school in", values, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolNotIn(List values) {
            addCriterion("junior_middle_school not in", values, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolBetween(String value1, String value2) {
            addCriterion("junior_middle_school between", value1, value2, "juniorMiddleSchool");
            return this;
        }

        public Criteria andJuniorMiddleSchoolNotBetween(String value1, String value2) {
            addCriterion("junior_middle_school not between", value1, value2, "juniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolIsNull() {
            addCriterion("senior_middle_school is null");
            return this;
        }

        public Criteria andSeniorMiddleSchoolIsNotNull() {
            addCriterion("senior_middle_school is not null");
            return this;
        }

        public Criteria andSeniorMiddleSchoolEqualTo(String value) {
            addCriterion("senior_middle_school =", value, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolNotEqualTo(String value) {
            addCriterion("senior_middle_school <>", value, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolGreaterThan(String value) {
            addCriterion("senior_middle_school >", value, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("senior_middle_school >=", value, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolLessThan(String value) {
            addCriterion("senior_middle_school <", value, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolLessThanOrEqualTo(String value) {
            addCriterion("senior_middle_school <=", value, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolLike(String value) {
            addCriterion("senior_middle_school like", value, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolNotLike(String value) {
            addCriterion("senior_middle_school not like", value, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolIn(List values) {
            addCriterion("senior_middle_school in", values, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolNotIn(List values) {
            addCriterion("senior_middle_school not in", values, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolBetween(String value1, String value2) {
            addCriterion("senior_middle_school between", value1, value2, "seniorMiddleSchool");
            return this;
        }

        public Criteria andSeniorMiddleSchoolNotBetween(String value1, String value2) {
            addCriterion("senior_middle_school not between", value1, value2, "seniorMiddleSchool");
            return this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("interest is null");
            return this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("interest is not null");
            return this;
        }

        public Criteria andInterestEqualTo(String value) {
            addCriterion("interest =", value, "interest");
            return this;
        }

        public Criteria andInterestNotEqualTo(String value) {
            addCriterion("interest <>", value, "interest");
            return this;
        }

        public Criteria andInterestGreaterThan(String value) {
            addCriterion("interest >", value, "interest");
            return this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(String value) {
            addCriterion("interest >=", value, "interest");
            return this;
        }

        public Criteria andInterestLessThan(String value) {
            addCriterion("interest <", value, "interest");
            return this;
        }

        public Criteria andInterestLessThanOrEqualTo(String value) {
            addCriterion("interest <=", value, "interest");
            return this;
        }

        public Criteria andInterestLike(String value) {
            addCriterion("interest like", value, "interest");
            return this;
        }

        public Criteria andInterestNotLike(String value) {
            addCriterion("interest not like", value, "interest");
            return this;
        }

        public Criteria andInterestIn(List values) {
            addCriterion("interest in", values, "interest");
            return this;
        }

        public Criteria andInterestNotIn(List values) {
            addCriterion("interest not in", values, "interest");
            return this;
        }

        public Criteria andInterestBetween(String value1, String value2) {
            addCriterion("interest between", value1, value2, "interest");
            return this;
        }

        public Criteria andInterestNotBetween(String value1, String value2) {
            addCriterion("interest not between", value1, value2, "interest");
            return this;
        }

        public Criteria andSkillIsNull() {
            addCriterion("skill is null");
            return this;
        }

        public Criteria andSkillIsNotNull() {
            addCriterion("skill is not null");
            return this;
        }

        public Criteria andSkillEqualTo(String value) {
            addCriterion("skill =", value, "skill");
            return this;
        }

        public Criteria andSkillNotEqualTo(String value) {
            addCriterion("skill <>", value, "skill");
            return this;
        }

        public Criteria andSkillGreaterThan(String value) {
            addCriterion("skill >", value, "skill");
            return this;
        }

        public Criteria andSkillGreaterThanOrEqualTo(String value) {
            addCriterion("skill >=", value, "skill");
            return this;
        }

        public Criteria andSkillLessThan(String value) {
            addCriterion("skill <", value, "skill");
            return this;
        }

        public Criteria andSkillLessThanOrEqualTo(String value) {
            addCriterion("skill <=", value, "skill");
            return this;
        }

        public Criteria andSkillLike(String value) {
            addCriterion("skill like", value, "skill");
            return this;
        }

        public Criteria andSkillNotLike(String value) {
            addCriterion("skill not like", value, "skill");
            return this;
        }

        public Criteria andSkillIn(List values) {
            addCriterion("skill in", values, "skill");
            return this;
        }

        public Criteria andSkillNotIn(List values) {
            addCriterion("skill not in", values, "skill");
            return this;
        }

        public Criteria andSkillBetween(String value1, String value2) {
            addCriterion("skill between", value1, value2, "skill");
            return this;
        }

        public Criteria andSkillNotBetween(String value1, String value2) {
            addCriterion("skill not between", value1, value2, "skill");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("create_time in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("create_time not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andProfessionIsNull() {
            addCriterion("profession is null");
            return this;
        }

        public Criteria andProfessionIsNotNull() {
            addCriterion("profession is not null");
            return this;
        }

        public Criteria andProfessionEqualTo(String value) {
            addCriterion("profession =", value, "profession");
            return this;
        }

        public Criteria andProfessionNotEqualTo(String value) {
            addCriterion("profession <>", value, "profession");
            return this;
        }

        public Criteria andProfessionGreaterThan(String value) {
            addCriterion("profession >", value, "profession");
            return this;
        }

        public Criteria andProfessionGreaterThanOrEqualTo(String value) {
            addCriterion("profession >=", value, "profession");
            return this;
        }

        public Criteria andProfessionLessThan(String value) {
            addCriterion("profession <", value, "profession");
            return this;
        }

        public Criteria andProfessionLessThanOrEqualTo(String value) {
            addCriterion("profession <=", value, "profession");
            return this;
        }

        public Criteria andProfessionLike(String value) {
            addCriterion("profession like", value, "profession");
            return this;
        }

        public Criteria andProfessionNotLike(String value) {
            addCriterion("profession not like", value, "profession");
            return this;
        }

        public Criteria andProfessionIn(List values) {
            addCriterion("profession in", values, "profession");
            return this;
        }

        public Criteria andProfessionNotIn(List values) {
            addCriterion("profession not in", values, "profession");
            return this;
        }

        public Criteria andProfessionBetween(String value1, String value2) {
            addCriterion("profession between", value1, value2, "profession");
            return this;
        }

        public Criteria andProfessionNotBetween(String value1, String value2) {
            addCriterion("profession not between", value1, value2, "profession");
            return this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("tags is null");
            return this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("tags is not null");
            return this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("tags =", value, "tags");
            return this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("tags <>", value, "tags");
            return this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("tags >", value, "tags");
            return this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("tags >=", value, "tags");
            return this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("tags <", value, "tags");
            return this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("tags <=", value, "tags");
            return this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("tags like", value, "tags");
            return this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("tags not like", value, "tags");
            return this;
        }

        public Criteria andTagsIn(List values) {
            addCriterion("tags in", values, "tags");
            return this;
        }

        public Criteria andTagsNotIn(List values) {
            addCriterion("tags not in", values, "tags");
            return this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("tags between", value1, value2, "tags");
            return this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("tags not between", value1, value2, "tags");
            return this;
        }

        public Criteria andHomeSiteIsNull() {
            addCriterion("home_site is null");
            return this;
        }

        public Criteria andHomeSiteIsNotNull() {
            addCriterion("home_site is not null");
            return this;
        }

        public Criteria andHomeSiteEqualTo(String value) {
            addCriterion("home_site =", value, "homeSite");
            return this;
        }

        public Criteria andHomeSiteNotEqualTo(String value) {
            addCriterion("home_site <>", value, "homeSite");
            return this;
        }

        public Criteria andHomeSiteGreaterThan(String value) {
            addCriterion("home_site >", value, "homeSite");
            return this;
        }

        public Criteria andHomeSiteGreaterThanOrEqualTo(String value) {
            addCriterion("home_site >=", value, "homeSite");
            return this;
        }

        public Criteria andHomeSiteLessThan(String value) {
            addCriterion("home_site <", value, "homeSite");
            return this;
        }

        public Criteria andHomeSiteLessThanOrEqualTo(String value) {
            addCriterion("home_site <=", value, "homeSite");
            return this;
        }

        public Criteria andHomeSiteLike(String value) {
            addCriterion("home_site like", value, "homeSite");
            return this;
        }

        public Criteria andHomeSiteNotLike(String value) {
            addCriterion("home_site not like", value, "homeSite");
            return this;
        }

        public Criteria andHomeSiteIn(List values) {
            addCriterion("home_site in", values, "homeSite");
            return this;
        }

        public Criteria andHomeSiteNotIn(List values) {
            addCriterion("home_site not in", values, "homeSite");
            return this;
        }

        public Criteria andHomeSiteBetween(String value1, String value2) {
            addCriterion("home_site between", value1, value2, "homeSite");
            return this;
        }

        public Criteria andHomeSiteNotBetween(String value1, String value2) {
            addCriterion("home_site not between", value1, value2, "homeSite");
            return this;
        }

        public Criteria andIntroIsNull() {
            addCriterion("intro is null");
            return this;
        }

        public Criteria andIntroIsNotNull() {
            addCriterion("intro is not null");
            return this;
        }

        public Criteria andIntroEqualTo(String value) {
            addCriterion("intro =", value, "intro");
            return this;
        }

        public Criteria andIntroNotEqualTo(String value) {
            addCriterion("intro <>", value, "intro");
            return this;
        }

        public Criteria andIntroGreaterThan(String value) {
            addCriterion("intro >", value, "intro");
            return this;
        }

        public Criteria andIntroGreaterThanOrEqualTo(String value) {
            addCriterion("intro >=", value, "intro");
            return this;
        }

        public Criteria andIntroLessThan(String value) {
            addCriterion("intro <", value, "intro");
            return this;
        }

        public Criteria andIntroLessThanOrEqualTo(String value) {
            addCriterion("intro <=", value, "intro");
            return this;
        }

        public Criteria andIntroLike(String value) {
            addCriterion("intro like", value, "intro");
            return this;
        }

        public Criteria andIntroNotLike(String value) {
            addCriterion("intro not like", value, "intro");
            return this;
        }

        public Criteria andIntroIn(List values) {
            addCriterion("intro in", values, "intro");
            return this;
        }

        public Criteria andIntroNotIn(List values) {
            addCriterion("intro not in", values, "intro");
            return this;
        }

        public Criteria andIntroBetween(String value1, String value2) {
            addCriterion("intro between", value1, value2, "intro");
            return this;
        }

        public Criteria andIntroNotBetween(String value1, String value2) {
            addCriterion("intro not between", value1, value2, "intro");
            return this;
        }

        public Criteria andSignatureIsNull() {
            addCriterion("signature is null");
            return this;
        }

        public Criteria andSignatureIsNotNull() {
            addCriterion("signature is not null");
            return this;
        }

        public Criteria andSignatureEqualTo(String value) {
            addCriterion("signature =", value, "signature");
            return this;
        }

        public Criteria andSignatureNotEqualTo(String value) {
            addCriterion("signature <>", value, "signature");
            return this;
        }

        public Criteria andSignatureGreaterThan(String value) {
            addCriterion("signature >", value, "signature");
            return this;
        }

        public Criteria andSignatureGreaterThanOrEqualTo(String value) {
            addCriterion("signature >=", value, "signature");
            return this;
        }

        public Criteria andSignatureLessThan(String value) {
            addCriterion("signature <", value, "signature");
            return this;
        }

        public Criteria andSignatureLessThanOrEqualTo(String value) {
            addCriterion("signature <=", value, "signature");
            return this;
        }

        public Criteria andSignatureLike(String value) {
            addCriterion("signature like", value, "signature");
            return this;
        }

        public Criteria andSignatureNotLike(String value) {
            addCriterion("signature not like", value, "signature");
            return this;
        }

        public Criteria andSignatureIn(List values) {
            addCriterion("signature in", values, "signature");
            return this;
        }

        public Criteria andSignatureNotIn(List values) {
            addCriterion("signature not in", values, "signature");
            return this;
        }

        public Criteria andSignatureBetween(String value1, String value2) {
            addCriterion("signature between", value1, value2, "signature");
            return this;
        }

        public Criteria andSignatureNotBetween(String value1, String value2) {
            addCriterion("signature not between", value1, value2, "signature");
            return this;
        }

        public Criteria andFansCountIsNull() {
            addCriterion("fans_count is null");
            return this;
        }

        public Criteria andFansCountIsNotNull() {
            addCriterion("fans_count is not null");
            return this;
        }

        public Criteria andFansCountEqualTo(Integer value) {
            addCriterion("fans_count =", value, "fansCount");
            return this;
        }

        public Criteria andFansCountNotEqualTo(Integer value) {
            addCriterion("fans_count <>", value, "fansCount");
            return this;
        }

        public Criteria andFansCountGreaterThan(Integer value) {
            addCriterion("fans_count >", value, "fansCount");
            return this;
        }

        public Criteria andFansCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("fans_count >=", value, "fansCount");
            return this;
        }

        public Criteria andFansCountLessThan(Integer value) {
            addCriterion("fans_count <", value, "fansCount");
            return this;
        }

        public Criteria andFansCountLessThanOrEqualTo(Integer value) {
            addCriterion("fans_count <=", value, "fansCount");
            return this;
        }

        public Criteria andFansCountIn(List values) {
            addCriterion("fans_count in", values, "fansCount");
            return this;
        }

        public Criteria andFansCountNotIn(List values) {
            addCriterion("fans_count not in", values, "fansCount");
            return this;
        }

        public Criteria andFansCountBetween(Integer value1, Integer value2) {
            addCriterion("fans_count between", value1, value2, "fansCount");
            return this;
        }

        public Criteria andFansCountNotBetween(Integer value1, Integer value2) {
            addCriterion("fans_count not between", value1, value2, "fansCount");
            return this;
        }

        public Criteria andFollowCountIsNull() {
            addCriterion("follow_count is null");
            return this;
        }

        public Criteria andFollowCountIsNotNull() {
            addCriterion("follow_count is not null");
            return this;
        }

        public Criteria andFollowCountEqualTo(Integer value) {
            addCriterion("follow_count =", value, "followCount");
            return this;
        }

        public Criteria andFollowCountNotEqualTo(Integer value) {
            addCriterion("follow_count <>", value, "followCount");
            return this;
        }

        public Criteria andFollowCountGreaterThan(Integer value) {
            addCriterion("follow_count >", value, "followCount");
            return this;
        }

        public Criteria andFollowCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("follow_count >=", value, "followCount");
            return this;
        }

        public Criteria andFollowCountLessThan(Integer value) {
            addCriterion("follow_count <", value, "followCount");
            return this;
        }

        public Criteria andFollowCountLessThanOrEqualTo(Integer value) {
            addCriterion("follow_count <=", value, "followCount");
            return this;
        }

        public Criteria andFollowCountIn(List values) {
            addCriterion("follow_count in", values, "followCount");
            return this;
        }

        public Criteria andFollowCountNotIn(List values) {
            addCriterion("follow_count not in", values, "followCount");
            return this;
        }

        public Criteria andFollowCountBetween(Integer value1, Integer value2) {
            addCriterion("follow_count between", value1, value2, "followCount");
            return this;
        }

        public Criteria andFollowCountNotBetween(Integer value1, Integer value2) {
            addCriterion("follow_count not between", value1, value2, "followCount");
            return this;
        }

        public Criteria andBlogCountIsNull() {
            addCriterion("blog_count is null");
            return this;
        }

        public Criteria andBlogCountIsNotNull() {
            addCriterion("blog_count is not null");
            return this;
        }

        public Criteria andBlogCountEqualTo(Integer value) {
            addCriterion("blog_count =", value, "blogCount");
            return this;
        }

        public Criteria andBlogCountNotEqualTo(Integer value) {
            addCriterion("blog_count <>", value, "blogCount");
            return this;
        }

        public Criteria andBlogCountGreaterThan(Integer value) {
            addCriterion("blog_count >", value, "blogCount");
            return this;
        }

        public Criteria andBlogCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("blog_count >=", value, "blogCount");
            return this;
        }

        public Criteria andBlogCountLessThan(Integer value) {
            addCriterion("blog_count <", value, "blogCount");
            return this;
        }

        public Criteria andBlogCountLessThanOrEqualTo(Integer value) {
            addCriterion("blog_count <=", value, "blogCount");
            return this;
        }

        public Criteria andBlogCountIn(List values) {
            addCriterion("blog_count in", values, "blogCount");
            return this;
        }

        public Criteria andBlogCountNotIn(List values) {
            addCriterion("blog_count not in", values, "blogCount");
            return this;
        }

        public Criteria andBlogCountBetween(Integer value1, Integer value2) {
            addCriterion("blog_count between", value1, value2, "blogCount");
            return this;
        }

        public Criteria andBlogCountNotBetween(Integer value1, Integer value2) {
            addCriterion("blog_count not between", value1, value2, "blogCount");
            return this;
        }

        public Criteria andPhotoCountIsNull() {
            addCriterion("photo_count is null");
            return this;
        }

        public Criteria andPhotoCountIsNotNull() {
            addCriterion("photo_count is not null");
            return this;
        }

        public Criteria andPhotoCountEqualTo(Integer value) {
            addCriterion("photo_count =", value, "photoCount");
            return this;
        }

        public Criteria andPhotoCountNotEqualTo(Integer value) {
            addCriterion("photo_count <>", value, "photoCount");
            return this;
        }

        public Criteria andPhotoCountGreaterThan(Integer value) {
            addCriterion("photo_count >", value, "photoCount");
            return this;
        }

        public Criteria andPhotoCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("photo_count >=", value, "photoCount");
            return this;
        }

        public Criteria andPhotoCountLessThan(Integer value) {
            addCriterion("photo_count <", value, "photoCount");
            return this;
        }

        public Criteria andPhotoCountLessThanOrEqualTo(Integer value) {
            addCriterion("photo_count <=", value, "photoCount");
            return this;
        }

        public Criteria andPhotoCountIn(List values) {
            addCriterion("photo_count in", values, "photoCount");
            return this;
        }

        public Criteria andPhotoCountNotIn(List values) {
            addCriterion("photo_count not in", values, "photoCount");
            return this;
        }

        public Criteria andPhotoCountBetween(Integer value1, Integer value2) {
            addCriterion("photo_count between", value1, value2, "photoCount");
            return this;
        }

        public Criteria andPhotoCountNotBetween(Integer value1, Integer value2) {
            addCriterion("photo_count not between", value1, value2, "photoCount");
            return this;
        }

        public Criteria andVideoCountIsNull() {
            addCriterion("video_count is null");
            return this;
        }

        public Criteria andVideoCountIsNotNull() {
            addCriterion("video_count is not null");
            return this;
        }

        public Criteria andVideoCountEqualTo(Integer value) {
            addCriterion("video_count =", value, "videoCount");
            return this;
        }

        public Criteria andVideoCountNotEqualTo(Integer value) {
            addCriterion("video_count <>", value, "videoCount");
            return this;
        }

        public Criteria andVideoCountGreaterThan(Integer value) {
            addCriterion("video_count >", value, "videoCount");
            return this;
        }

        public Criteria andVideoCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("video_count >=", value, "videoCount");
            return this;
        }

        public Criteria andVideoCountLessThan(Integer value) {
            addCriterion("video_count <", value, "videoCount");
            return this;
        }

        public Criteria andVideoCountLessThanOrEqualTo(Integer value) {
            addCriterion("video_count <=", value, "videoCount");
            return this;
        }

        public Criteria andVideoCountIn(List values) {
            addCriterion("video_count in", values, "videoCount");
            return this;
        }

        public Criteria andVideoCountNotIn(List values) {
            addCriterion("video_count not in", values, "videoCount");
            return this;
        }

        public Criteria andVideoCountBetween(Integer value1, Integer value2) {
            addCriterion("video_count between", value1, value2, "videoCount");
            return this;
        }

        public Criteria andVideoCountNotBetween(Integer value1, Integer value2) {
            addCriterion("video_count not between", value1, value2, "videoCount");
            return this;
        }

        public Criteria andVoiceCountIsNull() {
            addCriterion("voice_count is null");
            return this;
        }

        public Criteria andVoiceCountIsNotNull() {
            addCriterion("voice_count is not null");
            return this;
        }

        public Criteria andVoiceCountEqualTo(Integer value) {
            addCriterion("voice_count =", value, "voiceCount");
            return this;
        }

        public Criteria andVoiceCountNotEqualTo(Integer value) {
            addCriterion("voice_count <>", value, "voiceCount");
            return this;
        }

        public Criteria andVoiceCountGreaterThan(Integer value) {
            addCriterion("voice_count >", value, "voiceCount");
            return this;
        }

        public Criteria andVoiceCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("voice_count >=", value, "voiceCount");
            return this;
        }

        public Criteria andVoiceCountLessThan(Integer value) {
            addCriterion("voice_count <", value, "voiceCount");
            return this;
        }

        public Criteria andVoiceCountLessThanOrEqualTo(Integer value) {
            addCriterion("voice_count <=", value, "voiceCount");
            return this;
        }

        public Criteria andVoiceCountIn(List values) {
            addCriterion("voice_count in", values, "voiceCount");
            return this;
        }

        public Criteria andVoiceCountNotIn(List values) {
            addCriterion("voice_count not in", values, "voiceCount");
            return this;
        }

        public Criteria andVoiceCountBetween(Integer value1, Integer value2) {
            addCriterion("voice_count between", value1, value2, "voiceCount");
            return this;
        }

        public Criteria andVoiceCountNotBetween(Integer value1, Integer value2) {
            addCriterion("voice_count not between", value1, value2, "voiceCount");
            return this;
        }
    }
}
